### ISSUE TITLE
User Menu component gets cached at the dispatcher 

### ISSUE THREAD

**Issue by kaushalmall** [Adobe-Marketing-Cloud/asset-share-commons#101]
The user-menu component gets cached at the dispatcher. Probably a good idea to change the implementation for it to be client side. Although, hoping @davidjgonzalez @godanny86 has some ideas on how to exactly implement it. 

/cc @arpithaar @rahuldeou

**Comment by davidjgonzalez** [comment]
1. Add the profile store (probably could add the rest of context hub?) to ASC
2. Have the HTL write out the 2 states; Logged in and Anonymous state to the HTML; JS driven by context hub state toggles which block of HTML is visible, and if in logged in state, injects the user's name into the DOM (from the contexthub profile store).

There may be some trickery after logging out; atleast w ClientContext this state would remain sticky in cookies/localstorage and show an anon user as the logged in user; so there may have to be some clearing of the ContextHub profile store as part of the logout click, but TBD

**Comment by davidjgonzalez** [comment]
Fixed in v1.2.0
