### ISSUE TITLE
Sessions accumulating overtime degrading performance

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/asset-share-commons#103]
**CRITICAL BUG**

This issue should be resolved in v1.1.2

* https://github.com/Adobe-Marketing-Cloud/asset-share-commons/releases/tag/asset-share-commons-1.1.2
* https://bintray.com/asc/releases/asset-share-commons/1.1.2

-----

Upon further investigation w @godanny86 this looks like an issues with AEM QueryBuilder leaking the resolver resources (via `hit.getResource()`).  Attaching a SNAPSHOT build that fixes this by using the request's resource resolver to getResource(..) on the hit.getPath().

**Comment by davidjgonzalez** [comment]
POSSIBLE FIX VIA SNAPSHOT OF PATCH SLING RESOURCE RESOLVER BUNDLE:

[org.apache.sling.resourceresolver-1.5.35-SNAPSHOT.jar.rename.txt](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/1626520/org.apache.sling.resourceresolver-1.5.35-SNAPSHOT.jar.rename.txt)

Note; this has not been fully tested yet - adding here in case someone wants to try this out.

**Comment by godanny86** [comment]
We will wait to hear from an effected customer before closing this issue...

**Comment by justinedelson** [comment]
@andrewmkhoury can you clarify how this relates to Sling Models? Doesn't seem related to me, but perhaps I'm missing something.

**Comment by andrewmkhoury** [comment]
@justinedelson sorry for the noise.  Initially David was suspecting it was related, however, it is not.

**Comment by justinedelson** [comment]
@andrewmkhoury no problem.

**Comment by davidjgonzalez** [comment]
Initially looked like it was w getting model from wrapped request, but upon further investigation turned out it wasn’t.
