### ISSUE TITLE
Add CHANGELOG to project to start tracking changes

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/asset-share-commons#14]
This should be added for next commit.

* https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

**Comment by davidjgonzalez** [comment]
Fixed via #17

**Comment by justinedelson** [comment]
might want to install https://github.com/apps/update-changelog in this repo to keep reminding you to update the file.
