### ISSUE TITLE
[Question] Allow a standalone search bar to be added to a page that redirects to a search page

### ISSUE THREAD

**Issue by artdirk** [Adobe-Marketing-Cloud/asset-share-commons#146]
I'm not sure if components currently exist to accomplish this use case, but one of our business teams would like to include just a search bar on their landing page that redirects to a search page built from the Search Template.

Is this currently possible, or would a new flavor of the Search Bar component need to be created to support this use case?

**Comment by godanny86** [comment]
I think it is easier to create a one-off mini form for that purpose. The Search Bar on the Asset Share page has some JS tied to it. 

It would be a pretty simple form:

```
<form action="<location-of-search-page>.html">
    <input type="text" name="fulltext" /> <!-- search form -->
    <button type="submit">Search </button>
    <input type="hidden" name="layout" value="card or list" />
</form>

```

Come to think about it you might be able to do all this with the [AEM Core Form Components](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/form/container/v2/container)

**Comment by artdirk** [comment]
@godanny86, thanks for the response!

We'd ideally like to style it so it matches the Asset Share Commons look and feel, and I'll make sure I take this into consideration when looking into the form option.

I was thinking I may be able to extend the Asset Share Commons search bar component for this...

**Comment by artdirk** [comment]
@godanny86, I just wanted to let you know I extended the Asset Share Commons search bar component and was able to easily create a standalone search bar component that meets the business's needs.

Thanks again for the guidance!

**Comment by davidjgonzalez** [comment]
Super!!
