### ISSUE TITLE
Video treatment on the Asset Details page

### ISSUE THREAD

**Issue by artdirk** [Adobe-Marketing-Cloud/asset-share-commons#147]
One of our business teams is planning to upload a bunch of videos into AEM, and would like to make them available via their Asset Share for people to view.

When I upload a video into our AMS AEM 6.3 stage instance and view it on the Asset Share item details page the video cannot be played. Is there anything that needs to be configured within the Asset Share to allow a video to be played from the item details page, or is this something that's on the roadmap for a future release?

As an FYI, we're currently using Asset Share Commons version 1.1.2.

**Comment by artdirk** [comment]
I just tested uploading a video to our AMS AEM 6.3 stage instance and the thumbnail shows up on the Asset Share search page and the item details page, but there's still no way to play the video from within the Asset Share.

With this noted, it looks like my local AEM 6.3 environment is missing something that keeps the thumbnail from being shown on the Asset Share search and item details page, so the only outstanding item is determining if it would be possible to configure the video to be played from the item details page.

**Comment by godanny86** [comment]
As of now Asset Share Commons doesn't have any video preview/play functionality. I think it would be a new Video Renditions component that could play a preview of the video based on some pre-configured types. Marking this as an enhancement as others have asked about it.

**Comment by godanny86** [comment]
@artdirk are you envisioning something like how the ootb Assets UI does it?

![image](https://user-images.githubusercontent.com/8974514/37063270-de0abf0e-2166-11e8-927a-7020fe8f7ffe.png)

**Comment by artdirk** [comment]
Danny, thanks for the quick responses!

If it could be implemented in both the search results card (as in your example) and the item details page that would be ideal, but if it could just be implemented in the item details page that would probably meet the business requirements.

Out of curiosity, do you have any ideas regarding a rough timeframe as to when this functionality might be added? This could be a show-stopper for this one business team unless we can communicate out any known plans...

**Comment by davidjgonzalez** [comment]
@arpithaar this looks great!

Curious - what happens if a non-video asset is used on an Asset Details page with this component?

Also, which video file (rendition) will actually be played? Always the Original?

**Comment by arpithaar** [comment]
Hi @davidjgonzalez ,

1. If the video component is used for a non video asset, I tried to display the message like below. Should the message be authorable?
![image](https://user-images.githubusercontent.com/34283439/37971964-def93aa0-31f4-11e8-93a0-96d31bb26d31.png)

2. Yes, the original rendition is played . I guess its a good idea to make it authorable to select the rendition?

**Comment by davidjgonzalez** [comment]
@arpithaar i think a authorable "not a video asset" is a good idea; keeps it simple but somewhat extensible. I wonder if the default styles should try to make it a grey rectangle to keep the "flow" of the page? thats just CSS of course..

It might make sense to have the rendition selectable - i think we do that for the Image component... im only thinking if the original is massive... this is really a "preview" of video; so if they have a smaller/lower bitrate version that might be better for this usecase - they can always download the full (big) original if they need that one.. wdyt?

**Comment by arpithaar** [comment]
Yeah. It makes sense to make the rendition selectable. Shall take care of that. Thanks @davidjgonzalez

**Comment by arpithaar** [comment]
@artdirk 
Waiting to hear your thoughts.

**Comment by artdirk** [comment]
Hi @arpithaar,

Thanks so much for providing this solution! Let me run it by my team and our business partners who will be using the video functionality the most and report back.

Art

**Comment by davidjgonzalez** [comment]
@artdirk FYI - this has been merged as is - enhancements can of course be contributed for later versions.
