### ISSUE TITLE
[Bug] Include renditions text in the Download Modal reads "Include Renditions true"

### ISSUE THREAD

**Issue by artdirk** [Adobe-Marketing-Cloud/asset-share-commons#151]
In release 1.4.0 of Asset Share Commons I noticed that "true" is added to the end of "Include Renditions" in the Download Modal, per the following screenshot:

![image](https://user-images.githubusercontent.com/33265694/37676554-75706e4c-2c35-11e8-8ea0-82b71c7f5c0e.png)

I'm not sure if this is by design?

**Comment by davidjgonzalez** [comment]
Definitely a bug :) thanks for reporting

**Comment by davidjgonzalez** [comment]
Resolves via 239c389
