### ISSUE TITLE
Asset added to cart is gone from cart when moving from one page to another page

### ISSUE THREAD

**Issue by ayfengl** [Adobe-Marketing-Cloud/asset-share-commons#156]
Asset added to cart is gone from cart when moving from one page to another page

With the version 1.4.0 on AEM 6.4, we are seeing issue with the asset added to the cart missing after going to a different page.  This issue does not occurs with version 1.4.0 on AEM 6.3 SP1.

**Comment by godanny86** [comment]
@ayfengl I know this error is reproducible when ASC is deployed to a fresh 6.4 instance. Do you see the same behavior when upgrading an AEM instance on 6.3.1 + ASC -> 6.4 ?

**Comment by ayfengl** [comment]
@godanny86 we actually noticed this in an upgraded instance from AEM 6.3.1 + ASC 1.1.4 to AEM 6.4 and we apply the latest ASC 1.4.0 to take benefit of ASC fixes since then.

**Comment by godanny86** [comment]
Ok thanks

**Comment by godanny86** [comment]
The PR #158 fixes the persistent issue but still noticing that the **Remove from cart** label is not consistent after subsequent page refreshes. So there is still a little more work to be done before closing this out.
![image](https://user-images.githubusercontent.com/8974514/37977609-f0f5a6d2-3198-11e8-8dbe-fa52855efc19.png)

![image](https://user-images.githubusercontent.com/8974514/37977689-1d2ff6b2-3199-11e8-9b0e-f4f4b36fe605.png)

**Comment by davidjgonzalez** [comment]
Fixed
