### ISSUE TITLE
The logged-in user information disappears and reappears when moving from one page to another page

### ISSUE THREAD

**Issue by artdirk** [Adobe-Marketing-Cloud/asset-share-commons#163]
Within AEM 6.4 with asset-share-commons.ui.apps-1.4.1-SNAPSHOT.zip installed, the logged-in user information in the right rail disappears and reappears when moving from one page to another page (this appears to be similar in nature to issue 156).

I initially opened Daycare ticket 145638 (https://daycare.day.com/content/home/gapcom/gapcom_us/managed_services/145638.html) to track this issue, but Adobe AMS also suggested that I log it here.

**Comment by davidjgonzalez** [comment]
Hi art - are you saying in one page load the username shows properly, and when refreshing/navigating to a diff page the users name may disappear? And on refresh reappear?

**Comment by artdirk** [comment]
Hi David!

Yes, it's very strange, but it's not a page refresh that causes the user name to show up...it happens when I navigate away to another page or three and come back to the page where it didn't show up before. Here's an example of this on the Old Navy Asset Share site we created.

First time through - the "SOCIAL" page is missing the user name:

![image](https://user-images.githubusercontent.com/33265694/38169377-91189692-351d-11e8-8ff2-72e43aca0d32.png)

I then click on a few of the other site pages and return to the "SOCIAL" page and the user name now shows up:

![image](https://user-images.githubusercontent.com/33265694/38169390-d645b24a-351d-11e8-89da-76710eb01628.png)

Thanks!
Art

**Comment by arpithaar** [comment]
@davidjgonzalez ,
I guess there are some issues with contexthub eventing. The event used now is EVENT_STORE_UPDATED(it was "EVENT_STORE_READY" before).  Facing similar issues in Microsoft, tried using both the events, did not help. FYI.

cc: @kaushalmall

**Comment by vijknair** [comment]
@davidjgonzalez MSFT going live with their 3 major tenants in next couple weeks, this eventually came back as a blocker from UAT. Please find the snapshots here https://www.screencast.com/t/j027bInnbU.   I had a quick look at "profile.js" , on the init method, 

` function init(event, eventData) {
        **if (eventData && eventData.store === "profile") {**
            // Only perform this check when the profile store is updated
            // For some reason the event handler below triggers for all stores and not just the profile store.
            if (isAnonymous()) {
                showAnonymous();
            } else {
                showAuthenticated();
            }
        }
    }`

On the high lighted line, sometimes when the page loads, the value of 'eventData.store' is seen as 'segments' , eventually the 'showAuthenticated' method never get invoked.

So do we really need this check if (eventData && eventData.store === "profile") ?

As of now I have added a fix in Msft code, to call the 'showAuthenticated' method if profile display name is not available. Sample code below

`  function initProfile(e) {
       var authenticatedSection = ns.Elements.element(AUTHENTICATED_SECTION_ID);

       // if the Asset share commons JS is successful in creating the profile menu, you will have the HTML field
       // 'cmp-user-menu__profile-display-name' available on the page. So make the following call, only in the case ASC
       // profile menu malfunction
         if (isAnonymous() ) {
             showAnonymous();
         } else if(!authenticatedSection.find(ns.Elements.selector(AUTHENTICATED_DISPLAY_NAME_ID)).val()){
             // explicitly call the method and show
             showAuthenticated();
         }
     }

    // Fix for inconsistent User profile Menu - call on load - Remove this once ASC release the fix for this
    $(window).on('load',initProfile);`

Once we have a fix from ASC, we will remove this local fix.

**Comment by davidjgonzalez** [comment]
@vijknair  TBH  im not entirely sure if we need this check; i added that because that event handler was getting updated events for *EVERY* store (which seemed wrong/strange) ...  I really struggled to find the correct check/hook for this (even using ContextHub debugger).

In the example above, will it (potentially) flip between anonymous and authenticated until it finally rests on Authenticated?

With the current implementation, it looks like the profile store is never updated to trigger this event?

Any idea how this [1] is getting invoked when it breaks?

[1] https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/contexthub.js

**Comment by mrozati** [comment]
imho the user menu is only initiated on the first page load but not on subsequent ones. This is how it happens:

**On the first request**
when the profile store is empty or contains another user, we force a 
`profileStore.loadProfile(requestUser)` ([contexthub.js#L39](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/contexthub.js#L39))
which triggers an `store-updated` event. This event is caught in [profile.js#L85](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/user-menu/clientlibs/site/js/profile.js#L85) and calls the init method to display the user menu.

**On further requests**
the profile store has already contain the request user and we just trigger a `store-ready` event via 
`profileStore.announceReadiness()` ([contexthub.js#L41](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/contexthub.js#L41))
This event is not caught anywhere in profile.js and hence the `init()` method is not called. This is why the user menu remains empty.

So the solution is to bind both `store-ready` and `store-updated` events to call the init method, e.g.
```
    profile.eventing.on(ContextHub.Constants.EVENT_STORE_READY, init);
    profile.eventing.on(ContextHub.Constants.EVENT_STORE_UPDATED, init);
```
