### ISSUE TITLE
Asset detail page| Increase in meta data items shows grey bar at the bottom of the asset details authoring page

### ISSUE THREAD

**Issue by nandakishorem** [Adobe-Marketing-Cloud/asset-share-commons#168]
On the asset details page, the number of metadata items if increased beyond 8 rows (responsive grid items), page shows a grey bar at the bottom and the metadata items are overlapping with the grey bar. Attached the screenshot of the page.

<img width="1436" alt="screen shot 2018-04-04 at 3 44 32 pm" src="https://user-images.githubusercontent.com/13195070/38290549-1d059c96-381f-11e8-9dd9-40849c60c432.png">
<img width="1436" alt="screen shot 2018-04-04 at 3 43 35 pm" src="https://user-images.githubusercontent.com/13195070/38290550-1d729d3c-381f-11e8-979e-6a3f2d90981a.png">

**Comment by godanny86** [comment]
@nandakishorem checkout Pull Request #175 . I created a small package that contains the fix if you want to test it out locally: 
[rail-editor-fix-0.0.1.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/1915825/rail-editor-fix-0.0.1.zip)
