### ISSUE TITLE
For details page components like image, empty placeholder template does not work if placeholders are missing

### ISSUE THREAD

**Issue by kanika1901kapoor** [Adobe-Marketing-Cloud/asset-share-commons#182]
Pages like /en/home/details/image.html, /en/home/details/video.html resolve to placeholder asset from page properties. If that is not present, they fallback to default placeholder at /apps/asset-share-commons/resources/placeholder.png . 

Expected -  If the default placeholder is not present , a warning should be thrown in logs and the empty placeholder template as mentioned in core/wcm/components/commons/v1/templates.html should be displayed in author mode.

Actual -  An exception is seen in logs and in author mode, the component is not visible for authoring unless it is hovered over.

_> Caused by: org.apache.sling.scripting.sightly.java.compiler.SightlyJavaCompilerException: data-sly-call: expression evaluates to null.
at org.apache.sling.scripting.sightly.java.compiler.RenderUnit.callUnit(RenderUnit.java:70)_

Fix - the sly tags with data-sly-use.placeholderTemplate needs to wrap properly

**Comment by kanika1901kapoor** [comment]
@davidjgonzalez - I was referring to a minor issue - the empty placeholder (/apps/core/wcm/components/commons/v1/templates.html) not getting displayed if you do not have a placeholder configured in page properties

**Expected** - Empty placeholders
![image](https://user-images.githubusercontent.com/1798869/39572956-dde5f84e-4eee-11e8-8f15-bf6747f0bc25.png)

**Actual** - This is how the page (/content/asset-share-commons/en/light/details/image.html) gets displayed as of today
![image](https://user-images.githubusercontent.com/1798869/39573072-494886c4-4eef-11e8-9155-16ad268c4b5b.png)

**Comment by davidjgonzalez** [comment]
I think using Resource Status Providers is a simple (and most importantly unobtrusive) solution to this ... Modifying the core logic of components to handle these cases seems like adding unnecessary complexity for something that should be a "one time" issue (ie. once you fix these configurations, they probably wont happen again).

Search Page - Missing Results component
![image](https://user-images.githubusercontent.com/1451868/40889880-fedef66c-673b-11e8-99ed-4906854a3228.png)

Asset Details Page - Missing Placeholder Asset configuration
![image](https://user-images.githubusercontent.com/1451868/40889890-0e98a990-673c-11e8-83d1-36b07e4f1c09.png)
