### ISSUE TITLE
Allow expired assets to be excluded from search results

### ISSUE THREAD

**Issue by artdirk** [Adobe-Marketing-Cloud/asset-share-commons#184]
One of our business users accidentally published some expired assets and was surprised to see them available within Asset Share search results (the expectation was that expired assets should not be visible and available for people to download or share).

Does an option to exclude expired assets from Asset Share search results sound like a valid enhancement?

**Comment by godanny86** [comment]
Hi @artdirk I think you can achieve this with some advanced configurations of the hidden filter component:

![image](https://user-images.githubusercontent.com/8974514/39631427-1bfc2fc2-4f80-11e8-850b-0a037facc921.png)

I believe this will ensure any assets that have expired will not show up in search results. However if the user knew the direct path (or had bookmarked) to the Asset Details page nothing would prevent them from going there.

Here is the QueryBuilder debug page I used to figure out the values for the Hidden Filter: http://localhost:4502/libs/cq/search/content/querydebug.html?_charset_=UTF-8&query=type%3Ddam%3AAsset%0D%0Apath%3D%2Fcontent%2Fdam%2Fasset-share-commons%0D%0Aorderby%3D%40jcr%3Acontent%2Fjcr%3AlastModified%0D%0Aorderby.sort%3Ddesc%0D%0A1_group.1_property%3Djcr%3Acontent%2Fmetadata%2Fprism%3AexpirationDate%0D%0A1_group.1_property.operation%3Dnot%0D%0A1_group.2_relativedaterange.property%3Djcr%3Acontent%2Fmetadata%2Fprism%3AexpirationDate%0D%0A1_group.2_relativedaterange.lowerBound%3D0d%0D%0A1_group.p.or%3Dtrue

**Comment by godanny86** [comment]
Also make sure to double check the query performance/impact of this additional filter...

**Comment by artdirk** [comment]
@godanny86, thanks for the quick response and proposed solution! We'll do some testing on our end and report back if there are any performance implications.

**Comment by davidjgonzalez** [comment]
Yup - that should work! 

Should this be a flag in search results (exclude expired assets)?

**Comment by artdirk** [comment]
@davidjgonzalez, I think making this a search results flag is a great idea, as it would keep authors from having to understand any complex hidden filters.

**Comment by davidjgonzalez** [comment]
Closed vis #201

**Comment by preetsekhon94** [comment]
Hi david,

I have same kind of requirement where i expired assets should not show up on landing page(home page) but when i will search them through property filter then expired assets should display with other assets.
To achieve this i have excluded expired assets from search restrictions but now the issue i am facing is that i am not even able to search them through search filter.
How should i achieve this scenario?
Will hidden filter help me out in this case
