### ISSUE TITLE
[UX] Consolidate JS calls

### ISSUE THREAD

**Issue by godanny86** [Adobe-Marketing-Cloud/asset-share-commons#19]
Currently 5 separate JS calls are being made:
* /etc.clientlibs/asset-share-commons/clientlibs/clientlib-site.js
* /etc.clientlibs/asset-share-commons/clientlibs/clientlib-contexthub/cart.js
* /etc.clientlibs/asset-share-commons/clientlibs/clientlib-site/js/cart.js
* /etc.clientlibs/asset-share-commons/clientlibs/clientlib-theme/semanticui-light.js
* /etc.clientlibs/asset-share-commons/clientlibs/clientlib-base.js

Ideally these clientlibs can be embedded/consolidated so that there is only 2 or 3 calls. At a minimum site.js should not be included twice, once on its own and a second time inside clientlib-base.js.

**Comment by davidjgonzalez** [comment]
Fixed this in v1.2.0

**Comment by davidjgonzalez** [comment]
This had the doubley problematic side effect that some of the "site" clientlib JS was being executed twice (luckily it was benign, though wasteful)
