### ISSUE TITLE
Tags Filter Sorting

### ISSUE THREAD

**Issue by juliaetate** [Adobe-Marketing-Cloud/asset-share-commons#191]
Is there a way to alphabetically sort the tags output in the tags filter?

**Comment by godanny86** [comment]
No there does not appear to be, but this would be a nice enhancement. The tags are pulled using  `com.day.cq.tagging.TagManager` and I'm not exactly sure how that implementation works.

**Comment by davidjgonzalez** [comment]
@juliaetate WDYT?

![image](https://user-images.githubusercontent.com/1451868/40879677-93d73e30-6671-11e8-8dce-b13817ec2a83.png)

**Comment by juliaetate** [comment]
Beautiful! I can't wait!
