### ISSUE TITLE
Search does not work in IE11 - Missing findIndex() & find()

### ISSUE THREAD

**Issue by niksvers** [Adobe-Marketing-Cloud/asset-share-commons#195]
On IE11, the search button on the search page throws an exception : "Object doesn't support property or method 'findIndex()' ". You can see the exception in the console logs of the browser.

Because IE11 does not support findIndex() & find() methods for Array, the search button does not work.

Path to the JS file : ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/form-data.js

**Comment by davidjgonzalez** [comment]
@niksvers hows this look?

https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/199
