### ISSUE TITLE
License Rights are not working for an asset on asset share Page while sharing

### ISSUE THREAD

**Issue by anoopkumargarg** [Adobe-Marketing-Cloud/asset-share-commons#197]
License Rights are not working for an asset on asset share Page while sharing. Same is working for download and licence popup is coming properly
https://adobe-marketing-cloud.github.io/asset-share-commons/pages/actions/share/

**Comment by godanny86** [comment]
Hi @anoopkumargarg the share modal does not prompt a license agreement before sharing. The share results in an email that is sent with a link to the asset details page (not the asset itself). The user who receives the email would still need to agree to the license before downloading the assets.

**Comment by anoopkumargarg** [comment]
Thanks Daniel !!
