### ISSUE TITLE
Statistics Component -- More + never shows

### ISSUE THREAD

**Issue by juliaetate** [Adobe-Marketing-Cloud/asset-share-commons#198]
I'm not seeing the plus sign for my total assets on any instance I have, whether on the sample site for ACS or what I've built for my project when I've got it set to show all. I just get 250 total even when there are more files. ${component.more} never appears to return true.

**Comment by davidjgonzalez** [comment]
Hi @juliaetate - what version of ASC are you using? I swore this was fixed as part of a larger fix earlier (but perhaps not)
