### ISSUE TITLE
For mobile and tablet view, the filter rail is displayed below search results.

### ISSUE THREAD

**Issue by aasikka** [Adobe-Marketing-Cloud/asset-share-commons#204]
**Describe the bug**
For mobile and tablet view, the filter rail is displayed on clicking hamburger icon. We noticed an issue for version>1.5.2, that the filter rail appears below the search results. For earlier versions, the filter rail used to Slide left, which provided better user experience. 

Snapshot from 1.5.2: 
![1 5 2 filter rail](https://user-images.githubusercontent.com/19965960/42084659-deaacd2e-7bab-11e8-9e5c-62ee8b708443.PNG)

Expected behavior: 
![1 5 0 filter rail](https://user-images.githubusercontent.com/19965960/42084673-edbe4cbe-7bab-11e8-930a-4a4f1f19a7a4.PNG)

**Environment**
* AEM Version: 6.3
* Asset Share Commons Version: 1.5.2
* Author, Publish or both: Both

**To Reproduce**
1. Open page "/content/asset-share-commons/en/light.html" in Tablet/Mobile view
2. Click on Hamburger icon on top-right corner
3. Look for responsive filter rail. It would appear below the search results

**Expected behavior**
The responsive filter rail should Slide left for Tablet and mobile view

**Comment by davidjgonzalez** [comment]
Released in v1.6.0
