### ISSUE TITLE
download-dynamic-media - Download Options doesn't show

### ISSUE THREAD

**Issue by vasseure-ke** [Adobe-Marketing-Cloud/asset-share-commons#221]
**Describe the bug**
In the Download Dynamic Media Modal, if some presets are set, the presets dropdown doesn't show, and vice-versa. It should probably be the opposite.  
[download-dynamic-media.html line 83](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download-dynamic-media/download-dynamic-media.html)
```html
<select class="ui dropdown search" name="s7exportsettings"
                        data-sly-test="${download.imagePresets.size == 0}">
                    <option value="">${properties.imagePresetsPlaceholderText}</option>
                    <sly data-sly-list.imagePreset="${download.imagePresets}">
                        <option value="{imagepreset:${imagePreset}}">${imagePreset}</option>
                    </sly>
                </select>
```
Should probably be:
```html
<select class="ui dropdown search" name="s7exportsettings"
                        data-sly-test="${download.imagePresets.size != 0}">
                    <option value="">${properties.imagePresetsPlaceholderText}</option>
                    <sly data-sly-list.imagePreset="${download.imagePresets}">
                        <option value="{imagepreset:${imagePreset}}">${imagePreset}</option>
                    </sly>
                </select>
```

**Environment**
* AEM Version: 6.3 SP2
* Asset Share Commons Version: 1.6.0
* Author

**To Reproduce**
1. Add the Download Dynamic Media Modal component
2. Edit the component and add some presets

**Expected behavior**
The drop-down showing the different presets download option should show.

**Comment by davidjgonzalez** [comment]
Can you provide a PR with this fix?

**Comment by davidjgonzalez** [comment]
For others that find this, you can create ExternalRedirectDispatcher configurations that point to expression-based Dynamic Media endpoints.
