### ISSUE TITLE
'Back' button doesn't work on asset details page

### ISSUE THREAD

**Issue by jlecavalier** [Adobe-Marketing-Cloud/asset-share-commons#224]
**Describe the bug**
The back button (looks like the '<' symbol) is not a clickable link on the asset details page.

**Environment**
* AEM Version: 6.4
* Asset Share Commons Version: 1.5.0
* Author

**To Reproduce**
1. Go to <Hostname>/path/to/asset/details/page.html (you can just use the sample content provided here on github to generate a details page)
2. Click on the back button (looks like '<' symbol at top of page)
3. Nothing happens

**Expected behavior**
Should return to the parent page (in the sample content, the parent page is the search page)

**Additional context**
We found a workaround for this in our own project. In [this file](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/title/clientlibs/site/js/title.js) we changed line 27 from:
`$('.cmp-details-title a[data-asset-share-id="return-link"]').each(function(index, element) {`
to
`$('.cmp-details-title').each(function(index, element) {`

and we changed line 44 from
`$(element).attr("href", returnUrl);`
to
`$(element).wrapInner('<a href="' + returnUrl + '" />');`

This resolved the issue for us, but I wanted to know if there was a better solution to the problem.

Thanks for your consideration!

**Comment by godanny86** [comment]
Thanks, @jlecavalier for opening the issue! Is this reproducible in all browsers or just specific ones? Can you try and reproduce the bug in the latest release, 1.6.0?

**Comment by godanny86** [comment]
@jlecavalier I'm not able to reproduce this. Feel free to re-open if you have more information.
