### ISSUE TITLE
Editors do not show the standard workflow status messages

### ISSUE THREAD

**Issue by josephrignanese** [Adobe-Marketing-Cloud/asset-share-commons#227]
**Describe the bug**
The sites and experience fragments page editors no longer show the standard workflow status messages when a workflow is running on the page

**Environment**
* AEM Version: 6.3.2.0
* Asset Share Commons Version: 1.6.0, 1.6.2
* Author, Publish or both? Author

**To Reproduce**
1. Go to the Touch UI editor for a sites page
2. Start a workflow on the page (e.g. request to activate)
3. Observe that the workflow status indicator does not show on the top of the editor.

**Expected behavior**
When a workflow is running on the page the workflow status should show at the top of the editor.

**Screenshots**
The below screenshot shows expected behaviour. With 1.6.0 or 1.6.2 installed the blue status bar at the top is missing.
![2018-08-14_16-57-38](https://user-images.githubusercontent.com/17347917/44076518-ce8ae364-9fe3-11e8-92a3-1774a417aed4.png)

**Additional context**
Appears to be related to #202

**Comment by godanny86** [comment]
@josephrignanese thanks for raising this. Really strange behavior. I would have assumed that at a minimum these would have only effected Asset Share Details and Asset Share Search pages. Will take a look at the PR.

**Comment by godanny86** [comment]
@josephrignanese can you try and reproduce this on 6.4? I'm wondering if something changed in the way resource status provider is expected to work between 6.3 and 6.4...

**Comment by davidjgonzalez** [comment]
It looks like a bug (or enhancement request) with the ResourceProvider... AEM picks that LAST registered CompositeStatusType component (ie. config) and uses that.  So if you rebind the OOTB editor -> workflow config, that will "take over" and be used; basically its non-deterministic at runtime.

@josephrignanese looks like the best interim solution, with the downsides of:
1) If the OOTB (or a custom) CompositeStatusType is rebound after the ASC, that one will take over.
2) If AEM adds a new status type to the OOTB "editor", then that type will be hidden (until we add it to ours). Ideally this should only possibly happen once a quarter (with SP or GA).

IMO we should log an Adobe ticket requesting the feature be improved (by the product team) to aggregate all status types from matching CompositeStatusType configs.

**Comment by josephrignanese** [comment]
@davidjgonzalez agree, we can raise an enhancement request on this. The current behaviour is that if a composite status type has the same name as an actual status type, precedence is given to the actual status type. If two composite status types have the same name, it is undefined which one is used.
