### ISSUE TITLE
ASC 1.6.2 in maven repositories

### ISSUE THREAD

**Issue by Shaihuludus** [Adobe-Marketing-Cloud/asset-share-commons#229]
Hi I'm trying use ASC to extend my project and use to most recent version (1.6.2). However 1.6.2 artifacts (both jar and com.adobe.aem.commons:assetshare.ui.apps:zip:) are not present in maven repositories (checked main maven repository and http://repo.adobe.com/)

Are planning to release these artifacts. I wouldn't want to develop project without last fixes

**Comment by godanny86** [comment]
Yes, these artifacts should be released shortly. Sorry for the delay!

**Comment by godanny86** [comment]
These are now available: https://repo.adobe.com/nexus/content/groups/public/com/adobe/aem/commons/assetshare.core/1.6.2/

**Comment by Shaihuludus** [comment]
That's great. Thanks
