### ISSUE TITLE
Performance issue at search page with 90K assets

### ISSUE THREAD

**Issue by anoopkumargarg** [Adobe-Marketing-Cloud/asset-share-commons#234]
**Question?**
* What piece of functionality do you have a question about?
* What are you trying to achieve?

We are facing Performance issue on search page with 90 K assets (Some Assets size may be 2 GB as well). We are currently using 1.5.2 version of asset share commons. When more that 50 users are using the page , next users are not able to login on application and page is taking  50 sec to load. Please advice hardware sizing for such huge assets

**Comment by godanny86** [comment]
@anoopkumargarg have you done any [thread dump analysis](https://helpx.adobe.com/experience-manager/kb/thread-dump-analysis.html) to see if there are some objects using excessive memory? 

Is this on Author or Publish or both?

Recommendations around Asset Sizing can be found here: https://helpx.adobe.com/experience-manager/6-4/assets/using/assets-sizing-guide.html

This is also a good resource/checklist to go through: https://helpx.adobe.com/experience-manager/6-4/assets/using/best-practices-for-assets.html

**Comment by davidjgonzalez** [comment]
@anoopkumargarg did you build in any custom dynamic faceting into your asset share impl?

**Comment by davidjgonzalez** [comment]
@anoopkumargarg bump; can you let us know if faceting is being used?

If faceting is implemented then this is a serious issue we need to prioritize investigating

If faceting IS implemented, then this should be logged as an issue with Support, as Oak faceting is not supported by AEM's QB APIs. If you DO use custom faceting in ASC (or anywhere in AEM), it is known to be slow on large results sets (which is precisely why we don't provide any faceting with ASC OOTB).

**Comment by sanjay4d** [comment]
@anoopkumargarg bump; if you could answer David's question that would be helpful for a project I'm on. Also, if you did implement faceting (though they recommend not to do it for performance issues) how did you approach that development? My understanding is the QueryBuilder APIs are tightly coupled to ASC and implementing Oak faceting would be a very large core rewrite. Thanks.

**Comment by davidjgonzalez** [comment]
By way out offline communication, it sounds like this is due to a custom facet extraction scenario, which is known to be an issue with AEM QueryBuilder API + Oak. Closing as this project cannot do anything about this issue. 

If faceting is not being used, please re-open with details.
