### ISSUE TITLE
Date Range Filter is not sending "to" date automatically

### ISSUE THREAD

**Issue by Shaihuludus** [Adobe-Marketing-Cloud/asset-share-commons#240]
**Describe the bug**
When using Date Range Filter it is not sending "to" date to query

**Environment**
* AEM Version: 6.4.1
* Asset Share Commons Version: 1.6.3-SNAPSHOT and 1.6.2
* Author, Publish or both? both

**To Reproduce**
1. Go to Demo Search page our any other search page with Date Range filter
2. Use filter
3. Only "from date is send"
4. Change "to" date
5. Previous "to" date is send

**Expected behavior**
Current "to" date should be send

**Comment by davidjgonzalez** [comment]
+1 .. am able to reproduce based on instructions in the issue
