### ISSUE TITLE
Default sorting is not working

### ISSUE THREAD

**Issue by Shaihuludus** [Adobe-Marketing-Cloud/asset-share-commons#248]
This bug appeared after
https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/239 
fix was introduced

The default sort method on search results is not working. Sorting from sort component is working

**Environment**
* AEM Version: 6.4.1
* Asset Share Commons Version: 1.6.3-SNAPSHOT
* Both instances

**To Reproduce**
1. Go to authoring of demo search page
2. Change default sorting 
3. Go to preview/publish 
4. Results are not sorted as they should

**Expected behavior**
Default sort should be applied

The bug is probably connected with treating predicates groups. The problem is that order and orderby.sort should not have any additional group and what is worse these parameters have different groups
Fragment from my debugger:
"1_group.type" -> "dam:Asset"
"2_group.0_path" -> "/content/dam/global-asset-library"
"2_group.p.or" -> "true"
"3_group.mainasset" -> "true"
"4_group.property" -> "jcr:content/contentFragment"
"4_group.property.operation" -> "not"
"6_group.orderby" -> "@jcr:content/cq:name"
"7_group.orderby.sort" -> "asc"
"p.guessTotal" -> "500"
"p.limit" -> "24"

Additionally when I add sorting from sort component:
"1_group.type" -> "dam:Asset"
"2_group.0_path" -> "/content/dam/global-asset-library"
"2_group.p.or" -> "true"
"3_group.mainasset" -> "true"
"4_group.property" -> "jcr:content/contentFragment"
"4_group.property.operation" -> "not"
"6_orderby" -> "@jcr:content/metadata/dell:ingestedDate" -> this is added by sort component
"6_orderby.sort" -> "asc" -> this is added by sort component
"7_group.orderby" -> "@jcr:content/cq:name"
"8_group.orderby.sort" -> "asc"
"p.guessTotal" -> "500"
"p.limit" -> "24"

As you can see now I have both default sorting (which is not working) and sorting from sort component (this one is working)

The issue is that orderby cannot be added into group but has to be put directly under root

**Comment by godanny86** [comment]
PR #251 looks good @davidjgonzalez! @Shaihuludus do you mind checking out the develop branch when you get a chance to verify?

**Comment by Shaihuludus** [comment]
Hello, looks good now, thanks :)

**Comment by davidjgonzalez** [comment]
released in v1.6.4
