### ISSUE TITLE
Search Statistics Component breaks Search Paths

### ISSUE THREAD

**Issue by Shaihuludus** [Adobe-Marketing-Cloud/asset-share-commons#249]
If Search Statistics Component is added to page then search paths from Search Results stop work and it starts search 

**Environment**
* AEM Version: 6.4.1
* Asset Share Commons Version: 1.6.3-SNAPSHOT
* Both instances

**To Reproduce**
1. Go to 'Search Page'
2. Set Search paths /content/dam/<somepath> on Search Result Component
3. It works
4. Add search statistics component (to be rendered before Search Results Component- above for example)

**Actual**
Search results contains results from all dam 
"2_group.0_path" -> "/content/dam" is send 

**Expected behavior**
Search results still works on selected path

**Comment by Shaihuludus** [comment]
The problem is in 
```
search = modelCache.get(Search.class);
```
In SearchStatistics. It generates search but uses SearchStatistics as resource so no properties from SearchResults are used. The when search results component is rendered it has instance of Search in ModelCache but it is already wrong because it used SearchStatistics resource.

Im not sure what would be the best fix as both components are separate and we can't be sure in what order they will be called (if searchresults component would be first then problem would be solved)

Maybe path to searchresults component resource should be fixed on search template but I'm not sure if this is the best approach

**Comment by davidjgonzalez** [comment]
released in v1.6.4
