### ISSUE TITLE
Download Popup is not opening sometime for assets which are associated with Licence Rights

### ISSUE THREAD

**Issue by anoopkumargarg** [Adobe-Marketing-Cloud/asset-share-commons#258]
**Describe the bug**
Download Popup is not opening sometime for assets which are associated with Licence Rights.

**Environment**
* AEM Version: AEM 6.3+SP2
* Asset Share Commons Version: 1.5.2
* Author, Publish or both : Both

**Comment by davidjgonzalez** [comment]
@anoopkumargarg what happens instead? Is the HTTP request for the download modal issued? Does it return anything? Whats the HTTP status code?
