### ISSUE TITLE
Sorting parameter is not setting

### ISSUE THREAD

**Issue by Shaihuludus** [Adobe-Marketing-Cloud/asset-share-commons#263]
When I have default sorting set changing of order is not working. 

**Environment**
* AEM Version: 6.4.1
* Asset Share Commons Version: 1.6.3-SNAPHOT

**To Reproduce**
1. Go to 'Search page' with configured default sorting and sort component with this sorting
2. Sort component is showing correct sorting parameter and order
3. Change sort order
4. Nothing happens

**Expected behavior**
Sort order changes

The problem lies in query. When I change sort order only this parameter is send 
```
?orderby.sort=desc&layout=card&p.offset=0&p.limit=24
```
Probably sort component should always send orderby

**Comment by davidjgonzalez** [comment]
@Shaihuludus is this from /develop? Any idea what commit?

Ill try it out but there were a bunch of updates/fixes to sorting as of https://github.com/Adobe-Marketing-Cloud/asset-share-commons/commit/355237db7f8bdcf5ad74c746887a9c26229e2bfc

**Comment by Shaihuludus** [comment]
Yes from develop, after introducing sort component setting default sort from search result component.
Probably problem is sort component behaviour.
It has set parameter (example: filename) from default search result. But when I change sort order it "thinks" that only this was changed and adds only orderby.sort to query. It doesn't add parameter (filename) because it wasn't change on component.

**Comment by davidjgonzalez** [comment]
Gotcha - I’ll take a look before work this morning. Thanks!

**Comment by davidjgonzalez** [comment]
released in v1.6.4
