### ISSUE TITLE
ASC 1.6.4 included Core Components 2.1.0 which breaks backwards compat with in version AEM 6.3.1

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/asset-share-commons#275]
> Dependencies: In order to use the 2.1.0 release, you first need to deploy the following on an AEM 6.3.2.2 or AEM 6.4.1.0 instance:

From https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/releases

@arpithaar / @godanny86  - were were going to drag up the minimum requirements? This should be a bigger version bump then since its breaks out backwards compat.

Should roll back? (what was the compelling reason to upgrade?)

**Comment by godanny86** [comment]
@davidjgonzalez the reason was: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/192 you can't change the page policy theme in 6.4.
