### ISSUE TITLE
Way to override the page components

### ISSUE THREAD

**Issue by vasseure-ke** [Adobe-Marketing-Cloud/asset-share-commons#282]
**Is there a way to override the page components?**
* I tried to "override" the page components by creating my own page and Inheriting the asset share commons page component, but it didn't work. Is there a proper way to do it?
* I want to add additional configuration, and additional scripts, especially google tag manager

I think that what's blocking me is the fact that the variable:
**com.adobe.aem.commons.assetshare.configuration.impl.ConfigImpl#rootResourceTypes**
contains only **['asset-share-commons/components/structure/search-page']**.

The configuration page can only be of this type, and it doesn't work if i replace the search-page by my own component. I also tried to make my own implementation of com.adobe.aem.commons.assetshare.configuration.Config but it is called in multiple compoments through ModelCache...
Maybe making **com.adobe.aem.commons.assetshare.configuration.impl.ConfigImpl#rootResourceTypes** configurable would be nice but i might be missing something.

**Comment by davidjgonzalez** [comment]
Have you tried making your page impl cq:component set sling:resourceSuperType to the asc page resource type?

**Comment by davidjgonzalez** [comment]
@vasseure-ke did this work for you? since the check uses `.isResourceType(...)` ... resource type inheritance should be respected.

**Comment by vasseure-ke** [comment]
Hello @davidjgonzalez sorry for the delay, we might be in a different time zone (I'm in Japan).
Indeed this solution seems to work fine, I was obstinate in overcomplication.

My plan was to have the following inheritance pattern:
**asc-page -> custom-page -> custom-search-page**

But one of the following inheritence should work fine:
**asc-search-page -> custom-search-page**
**asc-search-page -> custom-page -> custom-search-page**

Thank you for taking the time to answer!

**Comment by davidjgonzalez** [comment]
Different time zones we are!! :)

We try to use this RT look up matter for anything that’s required RT look up - post back if you find it insufficient and we could look at creating something ou can config and drives the lists of RT per logical type.
