### ISSUE TITLE
Asset Details Page reference by Asset ID is not supported in AssetDetails404Servlet

### ISSUE THREAD

**Issue by vinaykhurana** [Adobe-Marketing-Cloud/asset-share-commons#287]
**Describe the bug**
Asset Details Page referenced by Asset ID is supported on Author. However on Publisher AssetDetails404Servlet throws 404 if we enable the feature. I believe it was missed during implementation as the servlet checks for request.getRequestPathInfo().getSuffixResource() which in case of Asset ID will always be null. Hence the 404 error.

**Environment**
* AEM Version: 6.3.2
* Asset Share Commons Version: 1.6.2
* Author, Publish or both  : Publisher

**To Reproduce**
1. Enable "Asset Details Reference by Asset ID" flag on both author and publisher.
2. Go to Asset Details page on author which works fine.
3. Go to Asset Detail page on publisher which throws 404 error.

**Expected behavior**
The asset details page should render fine on publisher as well.

**Comment by kaushalmall** [comment]
I believe @vinaykhurana already has a fix for this.
