### ISSUE TITLE
Callback for showing a modal

### ISSUE THREAD

**Issue by m-suchorski** [Adobe-Marketing-Cloud/asset-share-commons#290]
**Is your feature request related to a problem? Please describe.**
Opening up a cart modal could fire a callback so we can determine whether the modal is fully loaded and visible. That would create a possibility to fire SemanticUI functions (for creating a dropdown menu for example) in a clear and clean way.

**Describe the solution you'd like**
A simple callback for a `show` method would suffice. I'm already working on it, gonna edit with a PR link soon. This is a really small change that would make all the difference.

Edit: PR is ready: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/291

**Describe alternatives you've considered**
I've considered using both `MutationObserver` and an event for `DOMSubtreeChanged` which are both heavy in terms of performance - I'd like to use something much simpler and cleaner.

**Comment by davidjgonzalez** [comment]
Sorry - are you planning on adding a call back or is the event sufficient?

I merged the event PR but can revert
