### ISSUE TITLE
Change implementation of goToTop method

### ISSUE THREAD

**Issue by fgrzelak** [Adobe-Marketing-Cloud/asset-share-commons#294]
**Is your feature request related to a problem? Please describe.**
Current implementation changes `window.location.hash` which pushes state to browser's history. It prevents user of going back by browser's back button.

**Describe the solution you'd like**
We'd like goToTop to do what it's meant to - scroll the page up. `window.scrollTo(0, 0)` would solve this.

**Comment by fgrzelak** [comment]
PR: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/295

**Comment by davidjgonzalez** [comment]
Thanks @fgrzelak  - makes sense!
