### ISSUE TITLE
Cart's Download and Share modals throw errors

### ISSUE THREAD

**Issue by m-suchorski** [Adobe-Marketing-Cloud/asset-share-commons#296]
**Describe the bug**
When I click 'Download' or 'Share Selected' on the cart modal it properly shows the smaller modal about sharing/downloading but clicking 'Cancel' on these smaller modals closes the modal but leaves the overlay visible and sometimes show a console in error about transition. 

So to wrap that up - I open the modal, I click on 'Download' (or Share), I click Cancel and the smaller modal closes but overlay stays visible. I have to click again to hide the overlay. This event is somewhat random - sometimes it works. so if needed please try to do it few times, write something in inputs or wait few seconds.

I guess this is linked to the fact that now only one instance of the cart modal exists in the DOM. Sometimes the console error points to the transition event that cannot be finished on an object that doesn't exist anymore.

**Environment**
* AEM Version: 6.4
* Asset Share Commons Version: 1.6.8
* Author, Publish or both? Both

**To Reproduce**
1. Open up Cart Modal
2. Click on 'Download' or 'Selected'
3. Wait few seconds or type something in an input field
4. Click 'X' or 'Cancel'
5. Overlay stays visible

**Expected behavior**
Both modal and the overlay should become invisible after clicking 'X' or 'Cancel'.

**Comment by davidjgonzalez** [comment]
@m-suchorski 

Am i doing something incorrect to reproduce? As it seems to work for me ...

https://youtu.be/PeWv9rMLGDA

**Comment by m-suchorski** [comment]
Well, seems like if you can't reproduce it then its our internal issue somehow. Sorry for that, guys, there must be something we are missing but that's on our end to fix. Thanks!
