### ISSUE TITLE
Detail page image fallback fails

### ISSUE THREAD

**Issue by HitmanInWis** [Adobe-Marketing-Cloud/asset-share-commons#307]
**Describe the bug**
When the detail page is configured to show Web rendition, the fallback image is not used.  It seems that by default "Web rendition" will try to find a web rendition, but if not found will render `original`.  For a file like an Excel spreadsheet, `original` cannot be rendered, so you get a broken image on the page.

A potential workaround for this is to change the setting of Rendition Type to "Use 'Rendition File Name Regex' defined below" and specify a regex of `.*\.web\..*`, which solves the issue for Excel files.  However, PDF files, where `original` can actually render a thumbnail now use the placeholder which is a regression, making this workaround sub-optimal.

**Environment**
* AEM Version: 6.4
* Asset Share Commons Version: 1.6.0

**To Reproduce**
1. Install default Asset Share Commons
2. Find an Excel file via Asset Share
3. Open the detail page - will see a broken image

**Expected behavior**
An "original" rendition is only considered a valid "web" rendition on the detail page for types that are known to render correctly, else the fallback image is used.

**Comment by davidjgonzalez** [comment]
merged to develop and slated for 1.6.10
