### ISSUE TITLE
DXF image files do not use the fallback image on search results list

### ISSUE THREAD

**Issue by HitmanInWis** [Adobe-Marketing-Cloud/asset-share-commons#308]
**Describe the bug**
DXF images do not use the image fallback on the search listing page.

**Environment**
* AEM Version: 6.4
* Asset Share Commons Version: 1.6.0

**To Reproduce**
1. Install default Asset Share Commons
2. Load a .dxf file to your DAM (meta type `image/vnd.dxf`)
3. Execute a search on asset share where this file shows in the results list

**Expected behavior**
Placeholder image should display for DXF files, as they cannot be rendered from their `original` rendition.

**Comment by davidjgonzalez** [comment]
Example DXF file: 

[Tyrannosaurus.DXF.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/2519152/Tyrannosaurus.DXF.zip)

**Comment by davidjgonzalez** [comment]
merged to develop and slated for 1.6.10
