### ISSUE TITLE
Support CFs (Text CF and SCFs) in the AssetType computed property

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/asset-share-commons#32]
We should support Content Fragments in the Asset Type Computed Property.

We should at a minimum support the Content Fragments based on models introduced in 6.3 FP 19008 and the standard in AEM 6.4.

**Comment by godanny86** [comment]
I agree Content Fragments have a more limited use case, but should be supported. I think that SCF is a totally different pattern. Until a valid use case with SCF comes up I think we should exclude them.

**Comment by davidjgonzalez** [comment]
Thinking about this, we are asking double-duty from AssetType ComputedProperty. We are too mixing 2 discrete the notions:

* Business label -> What's shown on an asset's card
* Data type  -> Reflects the assets actual underlying asset structure ~> how to render it's details.

We saw this during the build out when the AssetType would return PPT, Doc, PDF instead of the generic "document".  From a biz POV, its much more valuable to understand in search the results is a PDF vs having to click into the details to surmise it is a PDF.

It seems we should have 2 CP's:

* AssetType -> Maps to the biz-friendly Label (Stays same, or maybe even shows things like PDF, PPT, Doc)
* AssetDetailsType -> Drives which Asset Details page will be used (Same logic as currentAsset Type but adds CF support)

**Comment by davidjgonzalez** [comment]
Replacing with #180; the discussions around CF vs SCF is misleading/confusing.
