### ISSUE TITLE
How to expose complete asset data to third party application?

### ISSUE THREAD

**Issue by anoopkumargarg** [Adobe-Marketing-Cloud/asset-share-commons#323]
I want to write one wrapper on top of asset share to expose all asset data in json format to third party application. Could someone please let me know , how can we do that ?

**Comment by davidjgonzalez** [comment]
What exactly do you mean by “all asset data”? AEM provides  http JSON APIs for interacting w the dam.
https://helpx.adobe.com/experience-manager/6-4/assets/using/mac-api-assets.html

Can you used these?

**Comment by davidjgonzalez** [comment]
@anoopkumargarg ASC doesn't have a JSON rendition, so you couldn't use ASC for this directly.

If you wanted you see if attaching Sling Model Exporters to the details Component Sling Models is helpful, but expect there may be a variety of challenges getting that working in a way thats useful to you as well.


ASC is basically just a wrapper for constructing QueryBuilder queries - so you could hit QueryBuilder to search for assets. From there you could use the p.hits on querybuilder to select the properties you want (per the results) or you could use the AEM Assets HTTP API to get each result and its metadata. 
The main gap I can see is that neither QB or the AEM Assets HTTP API are aware of Computed Properties, so you wouldn't get those.

Closing as we don't have any facilities to do this today.
