### ISSUE TITLE
[Question] Buttons under the Renditions header on the Item Details page download the rendition

### ISSUE THREAD

**Issue by artdirk** [Adobe-Marketing-Cloud/asset-share-commons#33]
The buttons under the Renditions header on the Asset Share Commons item details page (Asset Details Template) download the selected rendition when you click on them, but there's also a Download button on this page, and this could be misleading to the page viewer.

I would expect the buttons under the Renditions header to do something else (maybe replace the image on the item details page with the selected rendition?) other than a download, since there's already a download button?

**Comment by davidjgonzalez** [comment]
Perhaps the title should be “Direct Download Renditions”? The “problem” w the download functionality that leverages the OOTB asset download servlet is it includes the original and all rendition; Typcially 1) the thumbnail renditions are useless and 2) either the original or one of the other renditions is what’s desired. 

You can of course simply remove one or the other components from the asset details page as well.

**Comment by davidjgonzalez** [comment]
2 more cents -

the links for the renditions can be disabled (so it acts as an indicator of what renditions are available when you use the download button).

 a “light box” of renditions would likely be a “new” asset details image component.

**Comment by artdirk** [comment]
David, thanks so much for the quick responses! We were thinking the same thing you mentioned in your first response - Modifying the "Renditions" header to provide context as to what will happen if you click on one of the rendition buttons.

**Comment by davidjgonzalez** [comment]
@artdirk if its alright ill close this issue. We can open new issues for specific work if you'd be interested in contributing any of the more specific enhancements.
