### ISSUE TITLE
Unable to Override ComputedProperty if Service ID is Higher

### ISSUE THREAD

**Issue by brandonmaynard** [Adobe-Marketing-Cloud/asset-share-commons#333]
**Describe the bug**
I am attempting to Override LicenseImpl from asset share with a custom LicenseImpl. If asset share's LicenseImpl's service ID is lower than my custom one, my custom one is ignored and the following message is given in the logs: 
```
28.11.2018 16:47:59.595 *DEBUG* [0:0:0:0:0:0:0:1 [1543445279389] GET /content/some/path/my/asset-share.html HTTP/1.1] com.adobe.aem.commons.assetshare.content.impl.CombinedProperties ComputedProperty [ com.my.custom.package.assetshare.content.properties.impl.LicenseImpl ] with key [ license ] already provided by a better ranked implementation
```
In my custom LicenseImpl, I have set the `service.ranking` property to `Integer.MAX_VALUE` but that appears to not be working either.

**Environment**
* AEM Version: 6.4.2.0
* Asset Share Commons Version: 1.6.10
* Author, Publish or both? Both

**To Reproduce**
1. Create a custom LicenseImpl ComputedProperty
2. Deploy asset share first
3. Deploy the new custom LicenseImpl second
4. Go to `/system/console/status-Services` to see each LicenseImpl's service ID. The first one listed (will have the lower service ID) is the one asset share choses to use and omits any others with an debug log statement like the one mention above.
5. Stop and restart the asset share bundle (hopefully causing the asset share's LicenseImpl to be listed second and have a higher service ID)
6. Asset share will now choose your custom LicenseImpl rather than the OOTB LicenseImpl for asset share

**Expected behavior**
If I override a ComputedProperty (such as LicenseImpl in this example), there is a programmatic way for me to set my overridden ComputerProperty to rank/take precedence over asset share's ComputerProperty. 

**Screenshots**
N/A

**Additional context**
Here are my annotations for my custom LicenseImple:
```
@Component(
        service = ComputedProperty.class,
        property = {
                Constants.SERVICE_RANKING + "=" + Integer.MAX_VALUE
        }
)
@Designate(ocd = LicenseImpl.Cfg.class)
public class LicenseImpl extends AbstractComputedProperty<String> {
```

**Comment by davidjgonzalez** [comment]
[asset-share-commons.ui.apps-1.6.11-SNAPSHOT.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/2627405/asset-share-commons.ui.apps-1.6.11-SNAPSHOT.zip)

@brandonmaynard could you try the above SNAPSHOT build out and let me know if it resolves the issue? If it does ill work on some unit tests and PR it.

**Comment by brandonmaynard** [comment]
@davidjgonzalez thanks for the quick turnaround!

Unfortunately, that doesn't seemed to have solved the issue. After installing the provided package, my custom LicenseImpl is still being outranked by asset share's if the service ID is higher. Take a look at service statuses for both LicenseImpl below. You'll notice the asset share's LicenseImpl has a service ID of **51457** whereas my custom one has a service ID of **53536** causing mine to be omitted.
```
Service **51457** - [com.adobe.aem.commons.assetshare.content.properties.ComputedProperty] (pid: n/a)
  from Bundle 557 - Asset Share Commons - Core (com.adobe.aem.commons.assetshare.core), version 1.6.11.SNAPSHOT
    component.id: 4521
    component.name: com.adobe.aem.commons.assetshare.content.properties.impl.LicenseImpl
    label: License
    service.bundleid: 557
    service.scope: bundle
    types: metadata
  Using Bundle 516 - Apache Sling Models Implementation (org.apache.sling.models.impl), version 1.4.7.T20180205124646-b0647a3
  Using Bundle 557 - Asset Share Commons - Core (com.adobe.aem.commons.assetshare.core), version 1.6.11.SNAPSHOT
```
```
  Service **53536** - [com.adobe.aem.commons.assetshare.content.properties.ComputedProperty] (pid: n/a)
  from Bundle 549 - Project: Core Bundle (com.my.custom.package.core), version 1.0.0.SNAPSHOT
    component.id: 4685
    component.name: com.my.custom.package.assetshare.content.properties.impl.LicenseImpl
    label: License
    resourceTypeValues: my-value
    service.bundleid: 549
    service.ranking: 2147483647
    service.scope: bundle
    type: metadata
  Using Bundle 557 - Asset Share Commons - Core (com.adobe.aem.commons.assetshare.core), version 1.6.11.SNAPSHOT
```

Here is the output in the log:
```
29.11.2018 11:42:35.261 *TRACE* [0:0:0:0:0:0:0:1 [1543513354972] GET /content/some/path/my/asset-share.html HTTP/1.1] com.adobe.aem.commons.assetshare.content.impl.CombinedProperties Registered ComputedProperty [ com.adobe.aem.commons.assetshare.content.properties.impl.LicenseImpl ] with key [ license ]
29.11.2018 11:42:35.261 *DEBUG* [0:0:0:0:0:0:0:1 [1543513354972] GET /content/some/path/my/asset-share.html HTTP/1.1] com.adobe.aem.commons.assetshare.content.impl.CombinedProperties ComputedProperty [ com.my.custom.package.assetshare.content.properties.impl.LicenseImpl ] with key [ license ] already provided by a better ranked implementation
```

Let me know if you need anymore information or have any questions. Thanks for your help

**Comment by davidjgonzalez** [comment]
[asset-share-commons.ui.apps-1.6.11-SNAPSHOT.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/2630372/asset-share-commons.ui.apps-1.6.11-SNAPSHOT.zip)

Can you install that version (which has debug statements) and log @ debug: com.adobe.aem.commons.assetshare.content.properties.impl ?

Im mostly looking for these debug lines:

![image](https://user-images.githubusercontent.com/1451868/49242549-0b6dd400-f3d9-11e8-8053-ef4a6c5b345e.png)

if you restart your bundle, it should only rebind yours and i think those will be the interesting logs. Its helpful if you can set your Label to something unique (since it logs label and not the classname)

**Comment by brandonmaynard** [comment]
So it appears to be working with this new snapshot package, but I am going to do more testing to make sure. Did you happen to make any logical changes with this latest package? Or did you just add the debug statements? Either way, here is the logging info you requested:
```
29.11.2018 13:16:59.749 *DEBUG* [qtp705224560-21093] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Unbinding Computed Property: [ name: license ] - [ rank: 2147483647 ] - [ label: My Custom License ]
29.11.2018 13:16:59.753 *DEBUG* [qtp705224560-21093] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Computed Property by Rank: [ name: license ] - [ rank: 0 ] - [ label: License ]
29.11.2018 13:16:59.753 *DEBUG* [qtp705224560-21093] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Highest ranking Computed Property: [ name: license ] - [ rank: 0 ] - [ label: License ]
29.11.2018 13:17:03.108 *DEBUG* [qtp705224560-21091] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Binding Computed Property: [ name: license ] - [ rank: 2147483647 ] - [ label: My Custom License ]
29.11.2018 13:17:03.108 *DEBUG* [qtp705224560-21091] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Computed Property by Rank: [ name: license ] - [ rank: 2147483647 ] - [ label: My Custom License ]
29.11.2018 13:17:03.108 *DEBUG* [qtp705224560-21091] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Highest ranking Computed Property: [ name: license ] - [ rank: 2147483647 ] - [ label: My Custom License ]
29.11.2018 13:17:03.108 *DEBUG* [qtp705224560-21091] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Computed Property by Rank: [ name: license ] - [ rank: 0 ] - [ label: License ]
```
Thank you again for your help with this. I really appreciate it

**Comment by davidjgonzalez** [comment]
nope - just the debug logs... I thought your initial logs looked strange since there shouldn't be any way to get 2 ComputedProperties with the same "getName()" into CombinedProperties anyhow.. this new `ComputedProperties.getComputedProperties()` basically dedupes the all Computed Property's by getName() and old exposes the highest ranking one.

Btw - can you stop your LicenseImpl component (/system/console/components) and verify that the OOTB one kicks back in? (the unbind hook should handle it)

Here's the diff of what i sent now vs last night:
![image](https://user-images.githubusercontent.com/1451868/49247540-86d58280-f3e5-11e8-875f-c92c5c02c464.png)

**Comment by brandonmaynard** [comment]
When I disable my custom LicenseImpl, I get the following log statements verifying that the OOTB one kicks back in:
```
29.11.2018 14:07:45.058 *DEBUG* [SCR Component Actor] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Unbinding Computed Property: [ name: license ] - [ rank: 2147483647 ] - [ label: My Custom License ]
29.11.2018 14:07:45.058 *DEBUG* [SCR Component Actor] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Computed Property by Rank: [ name: license ] - [ rank: 0 ] - [ label: License ]
29.11.2018 14:07:45.058 *DEBUG* [SCR Component Actor] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Highest ranking Computed Property: [ name: license ] - [ rank: 0 ] - [ label: License ]
29.11.2018 14:09:19.035 *DEBUG* [0:0:0:0:0:0:0:1 [1543522158805] GET /content/some/path/my/asset-share.html HTTP/1.1] com.adobe.aem.commons.assetshare.content.properties.impl.ComputedPropertiesImpl Computed property: [ name: license ] - [ label: License ]
```
I am still doing more testing and will report back in a couple of hours.

**Comment by brandonmaynard** [comment]
@davidjgonzalez after doing more testing, I can definitely say that there are some differences between the 2 `asset-share-commons.ui.apps-1.6.11-SNAPSHOT.zip` packages. Using the first one you supplied, the ranking issue still exists also. Using the second one you supplied, the issue appears to be fully resolved and working as expected. Also, there is a few UI differences as well.

Using the first package:
<img width="225" alt="before" src="https://user-images.githubusercontent.com/32407610/49252510-d5851b80-f3e9-11e8-80b1-ea204e2621f0.png">

Using the second package:
<img width="231" alt="after" src="https://user-images.githubusercontent.com/32407610/49252532-de75ed00-f3e9-11e8-96e5-a7a3e2bf2df3.png">

**Comment by davidjgonzalez** [comment]
Ahh yup. That package must not have gotten rebuilt after I cleaned my working code base - that title2 was a test computed property I was using. Sorry about that. The latest w debug is what’s in the PR.

**Comment by brandonmaynard** [comment]
Yep, thank you so much for your assistance with this - well done
