### ISSUE TITLE
Race Condition With License Modal to Download Modal

### ISSUE THREAD

**Issue by brandonmaynard** [Adobe-Marketing-Cloud/asset-share-commons#337]
**Describe the bug**
This is directly related to, and duplicates:
- https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/258
- https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/270

Depending on which POST completes first (license modal or download modal), the download modal does not pop up when accepting the License Terms & Condtions. 
_In my testing, this works as expected ~85% of the time_

Both POSTs for the license modal and the download modal are executed almost simultaneously when attempting to download an asset that is set up as a licensed image:
![image](https://user-images.githubusercontent.com/32407610/49265543-27dd3100-f418-11e8-9cee-526296ffb56c.png)

If the download modal's POST completes before the license modal's POST, the download modal will not show up after accepting. Instead, the license modal will just close. Also, the following error will appear in the browser's console: `Modal: The element you specified could not be found [data-asset-share-id="license-modal"] [data-asset-share-id="license-accept"]`

**Environment**
* AEM Version: 6.4.2.0
* Asset Share Commons Version: 1.6.10
* Author, Publish or both? Both

**To Reproduce**
1. Navigate to `/content/asset-share-commons/en/dark.html?fulltext=sarah&layout=card&p.offset=0&p.limit=4`
2. Click on `sarah-dorweiler-357959.jpg` download button (see image below step 5) to trigger the license modal (this image is set up as a licensed image OOTB)
3. Accept the license agreement
4. If the download modal shows up, close the modal (don't refresh the page)
5. Repeat steps 2-4 until the download modal does not show up and the license modal just closes
![image](https://user-images.githubusercontent.com/32407610/49265962-e9e10c80-f419-11e8-8dbe-511cab9ffd00.png)

**Expected behavior**
UI: When accepting the license modal, the download modal always displays right after. 
Technical: The license modal's POST always completes before the download modal's POST completes

**Screenshots**
N/A

**Additional context**
The logic for fetching the license modal and download modal is found on `/apps/asset-share-commons/clientlibs/clientlib-site/js/semantic-ui/modal.js` at line 83 (`$.post(modal.url, modal.data, function (htmlResponse) {`)

The `modals` object on the forEach loop on line 81 contains both the following objects:
```
0: {id: "license-modal", url: "/content/my/path/asset-share/actions/license.partial.html%2Fcontent%2Fdam%2Fhelloworld%2Fprivate%2SpiderCloud%20Radio%20Node.jpg", data: {…}, options: {…}}
1: {id: "download-modal", url: "/content/my/path/asset-share/actions/download.partial.html", data: {…}, options: {…}}
```

**Comment by HitmanInWis** [comment]
In short, this is a classic AJAX race condition.

95% of the time (i.e. it works) it happens like this:
1. License Modal request
2. Download Modal request
3. License Modal response
4. Download Modal request
4b. Download Modal code instruments License modal

5% of the time (i.e. it breaks) it happens like this:
1. License Modal request
2. Download Modal request
3. Download Modal request
3b. Download Modal code instruments License modal **(FAIL - it doesnt exist yet)**
4. License Modal response

**Comment by davidjgonzalez** [comment]
@brandonmaynard check out #338 if you have a moment; this basically moves the AJAX call for subsequent modals into the "html response handler" function of the prior modal - so it should force a synchronous modal call stack.

**Comment by brandonmaynard** [comment]
@davidjgonzalez I was not able to get the race condition after using your new modal.js code. Thanks again for the quick turnaround

**Comment by davidjgonzalez** [comment]
@brandonmaynard np! Thanks for the thorough bug reports - makes much faster to understand and fix!
