### ISSUE TITLE
Dynamic Media Download modal

### ISSUE THREAD

**Issue by artdirk** [Adobe-Marketing-Cloud/asset-share-commons#34]
@mahendraramesh is picking this up (not part of the AMC org so i cant assign it to him :() - using  myself as a placeholder.

-----

Would it be possible to add Dynamic Renditions as a Download modal option if Dynamic Media is enabled within AEM?

Also see #46 (duplicate) of this.

**Comment by davidjgonzalez** [comment]
@artdirk i'd have to take a look at how how the OOTB download works. 
For the ASC download functionality, we leverage the OOTB Assets Download servlet directly; IE

`HTTP GET /content/dam.assetdownload.zip?path=/path/to/assets&<and the other checkbox based params>`

Assuming DM uses this same servlet (IDK if it does off the top of my head) i'd expect we'd want to augment the download modal component (or create a new) as follows:

* Create some User facing form control in the modal that lists the available DM renditions to download (Or if the set if author defined, set in dialog).
* Make this this form control sets the correct query params for the GET to the assetdownload.zip servlet.

If its an entirely different servlet, i think the most straight route would be to copy the Download Modal and supporting Model into a new Component and make the necessary changes there. I suspect it's just figuring out what Servlet to hit and what QParams to pass (which can be easily found by looking at the OOTB HTTP traffic on an instance running DM)

**Comment by mahendraramesh** [comment]
@davidjgonzalez for DM, an additional param s7exportsettings is passed to the same servlet.

**Comment by davidjgonzalez** [comment]
@artdirk FYI - @mahendraramesh is looking at picking this up; We discuss the strategy of creating a new DM Download Modal component that has the option to download

* The original 
* Configured DM Renditions

if this component is added and DM is not enabled,
* On author it will note that DM must be enabled, and if it is not to use the Download Modal component
* On Publish .... TBD :)

If you have thoughts/recommendations on this approach please drop them in the GH issue.
