### ISSUE TITLE
Asset Share modals are broken by Apache ModSecurity (URLs not properly escaped)

### ISSUE THREAD

**Issue by HitmanInWis** [Adobe-Marketing-Cloud/asset-share-commons#340]
**Describe the bug**
Asset share modal POSTs are blocked by ModSecurity rule 950109 ("Multiple URL Encoding Detected").  This prevents modals from working on secure apache installs.

**Environment**
* AEM Version: N/A
* Asset Share Commons Version: 1.6.10
* Author, Publish or both? Apache Dispatcher

**To reproduce**
- Enable ModSecurity on your apache dispatcher
- Attempt to open modals (download, cart, email, license) - they will fail with HTTP 403

**Expected behavior**
Download, Cart, Email, and License modals open when requested via dispatcher :)

**Additional context**
The crux of the issue is that the URLs are double encoded.  They are encoded when they are entered by JavaScript into the `form` as encoded values.  Then when the form submits, they are encoded again. 

Stated simply
1. Path is /content/dam/myasset.jpg
2. Path in form data is %2Fcontent%2Fmyasset.jpg
3. Path submitted via POST is %252Fcontent%252Fmyasset.jpg **This gets blocked by ModSecurity**

**Comment by HitmanInWis** [comment]
Note that the double encoding seems unnecessary.  I tested passing single encoded paths and at least the download modal seems to work correctly.

**Comment by HitmanInWis** [comment]
And to be fully honest, I know the Download, Email, and Cart modals are broken by this.  I actually still have to see if License is affected by this.

**Comment by davidjgonzalez** [comment]
This seems to have been caused #298

**Comment by kaushalmall** [comment]
@sandeep-prasad can you please look into this? I don't remember what we did here :-(

**Comment by HitmanInWis** [comment]
My tested solve doesn't work.  Basically I think ModSecurity is checking for anything that is double encoded, so even spaces that start as %20 and become %2520 in the request are nixed by ModSecurity :-/

**Comment by davidjgonzalez** [comment]
It seemed the problem was when extended characters were in the path, they were not being encoded properly in transit and thus could not be understood serverside.

**Comment by davidjgonzalez** [comment]
@HitmanInWis can you provide the sample Request that has the double-encoded content? (what the browser is sending).  is the double encoding only incurring in file paths? or in other params as well?
IIRC the explicit encoding (via #298/303) was added because no encoding was taking place on the paths?

**Comment by HitmanInWis** [comment]
@davidjgonzalez, its pretty much all POST requests that send a path.  Easiest to repro is to click a download link on an asset.  There should not be a need to encode the path, because the form contents are already encoded when sent via the AJAX request, thus causing the double encode.

**Comment by davidjgonzalez** [comment]
[IRA SAMPLES ASSETS.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/2649172/IRA.SAMPLES.ASSETS.zip)

I created a sampling of weirdly named assets to help validate this ... These show existing gaps and also indicate that this problem is going to be much harder to solve :(

I think we need to make sure we're using the right encoders vs escaping throughout as well.

**Comment by davidjgonzalez** [comment]
I believe this can be used to escape URLs: https://jackrabbit.apache.org/api/2.8/org/apache/jackrabbit/util/Text.html#escape(java.lang.String)

Note we need to escape not encode.

also, it appears HTL cannot be extended to apply to escape in the HTL script, rather we need to expose this in the Java/SModel level.
