### ISSUE TITLE
Create a cacheable, renditions servlet

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/asset-share-commons#345]
**Is your feature request related to a problem? Please describe.**
Currently, the best (only?) way to directly access in ASC over HTTP is to make HTTP GETs to `/content/dam/the-asset.png/_jcr_content/some-rendition.png`. This is problematic for 3 reasons:
1) It can result in /contnet/dam/the-asset.png being created as a folder in dispatcher preventing the caching of the actual asset file.
2) It leaks and relies on the implementation details of how AEM stores static renditions to the consumer.
3) It makes it difficult to serve renditions that aren't static asset renditions in a uniform manner (Ie. if a dynamic watermarked rendition is desired, a different rendition request approach is required.

**Describe the solution you'd like**
An AssetRenditionServlet that allows a named rendition to be requested. For example, something like:

* `HTTP GET /content/dam/the-asset.png.rendition/web.img`
* `HTTP GET /content/dam/the-asset.png.rendition/original.img`
* `HTTP GET /content/dam/the-asset.png.rendition/thumbnail.img`

**Additional context**

This would start as proxying the static rendition streams out but should be designed in a way where the public API is extensible where the URL params (suffix) could drive dynamic renditions as well (including possibly? Dynamic Media urls)

**Comment by joerghoh** [comment]
Hm, is https://adobe-consulting-services.github.io/acs-aem-commons/features/named-image-transform/index.html not sufficient?

**Comment by davidjgonzalez** [comment]
@joerghoh its similar use case, but different.

NIT only works against a (single) configurable rendition (by default the web rendition); so this satisfies a similar-ish, however different use-case.

I think this solution SHOULD support the use of NIT (assuming it properly responds to request dispatcher include/forwards).

Ex.

`HTTP GET /content/dam/the-asset.png.rendition/my-nit.img` -> some form of include/fwd/redirect ->  `~ HTTP GET /content/dam/the-asset.png.transform/some/mapped/transforms/image.ext`

IMO this servlet should mostly be a "dumb" proxy to other things which determine what the rendition is (if that makes sense).

Also, ASC shouldn't depend on ACS Commons (it can optionally leverage, but not have key functionality require it)

**Comment by joerghoh** [comment]
We should avoid duplicating functionality, even it's not an exact match. I don't mind having a dependency from ASC to acs-aem-commons.

I would suggest to extend the NIT of acs-aem-commons functionality in a way that it satisfies the needs to ASC. The usecase is not that unique to ASC, from my point of view it makes sense to maintain it in acs-aem-commons.

**Comment by davidjgonzalez** [comment]
sure - but like i said, its not. 

NIT is intended to TRANSFORM functionality. This is intended to provide a mappable rendition for assets only. This could (and ideally would) support mapping a URL to a Dynamic Media URL, which NIT should *never* do.

**Comment by davidjgonzalez** [comment]
Anyhow - ill build it into ASC code base for now in a modular manner, and at PR we can review and determine what makes sense for where it should ultimately live, and what a new external dep would mean for ASC (we took the time to remove the ACS Commons dependency earlier already) - @godanny86  can provide thoughts on thoughts of another ~hard dep (we already have Core Components which no longer thrills me due to BC issues).

**Comment by godanny86** [comment]
@davidjgonzalez noticing several issues related to PR #411 on AEM 6.3 + SP1. Do you want to me to create a new issue or keep it consolidated here?
