### ISSUE TITLE
Path filter is not saving the value attribute

### ISSUE THREAD

**Issue by viveknextrow** [Adobe-Marketing-Cloud/asset-share-commons#346]
**Describe the bug**
Path filter is not saving the value attribute

**Environment**
* AEM Version: 6.3.2.2
* Asset Share Commons Version: 1.6.2
* Author, Publish or both? - Author

**To Reproduce**
1. Go to path /content/asset-share-commons/en/dark.html
2. In the bottom parsys, select the "Path Filter" component from the component group "ASSET SHARE COMMONS - SEARCH"
3. edit the path filter component, add the title and under the options, add label and the path * and save it.
4. After saving, path filter component looks grayed out on the UI and the value for teh option field is missing  when we again edit the component. In crxde, under the items value is not being saved. Only Text attribute is saved. This is the error.

**Expected behavior**
When saving the options in the path filter along with the text and value, both should be saved.
<img width="612" alt="screen shot 2018-12-11 at 12 15 13 pm" src="https://user-images.githubusercontent.com/38136093/49820785-7060ec80-fd3e-11e8-9b57-8a96ff90f9d3.png">

**Screenshots**
<img width="1035" alt="screen shot 2018-12-11 at 12 14 32 pm" src="https://user-images.githubusercontent.com/38136093/49820749-57f0d200-fd3e-11e8-9d51-6043455ffa8b.png">
<img width="615" alt="screen shot 2018-12-11 at 12 18 38 pm" src="https://user-images.githubusercontent.com/38136093/49820969-e9604400-fd3e-11e8-96d5-17d4794a67fd.png">
<img width="655" alt="screen shot 2018-12-11 at 12 19 04 pm" src="https://user-images.githubusercontent.com/38136093/49820996-fa10ba00-fd3e-11e8-8703-9162868552d5.png">

**Additional context**

**Comment by godanny86** [comment]
Hi @viveknextrow can you reproduce this issue using Asset Share Commons 1.6.10?

**Comment by godanny86** [comment]
It may also be helpful to capture the XHR POST request using the browser's developer tools to see what form data is being posted to AEM when saving the dialog:

![image](https://user-images.githubusercontent.com/8974514/50100969-a0e9d000-01ef-11e9-8f82-932763eca5d7.png)

**Comment by viveknextrow** [comment]
> Hi @viveknextrow can you reproduce this issue using Asset Share Commons 1.6.10?

Hello @godanny86 - yes, I am able to reproduce the issue with Asset Stare commons Version 1.6.10 as well.

**Comment by viveknextrow** [comment]
> It may also be helpful to capture the XHR POST request using the browser's developer tools to see what form data is being posted to AEM when saving the dialog:
> 
> [](![image](https://user-images.githubusercontent.com/8974514/50100969-a0e9d000-01ef-11e9-8f82-932763eca5d7.png))

attached is the XHR POST call where the values are being passed. The property which is not being stored is passed as "value : /content/dam/asset-share-commons", whereas the text is being saved as - "test1" with the property as ".items/item0/text" 

![screen shot 2018-12-17 at 12 26 48 pm](https://user-images.githubusercontent.com/38136093/50107126-5ec48c80-01f7-11e9-8f04-8c3d64cf14f4.png)

**Comment by godanny86** [comment]
Ah, so it looks like an issue with the dialog... what version of Core Components are active?

Also curious if you update to AEM 6.3 + SP3 what happens?

**Comment by viveknextrow** [comment]
Hello @godanny86  - core component version is - 1.1.0. We are on AEM 6.3.2.2 (6.3 + SP2).

**Comment by godanny86** [comment]
If it is just 6.3 + SP2 I think the version would be 6.3.2.0, so you have another FP installed? Will have to see if I can reproduce, I was just using 6.3.2.0

**Comment by viveknextrow** [comment]
We are on AEM 6.3.2.2. We had installed security fixes from Cumulative Fix Pack 6.3.2.2.
https://helpx.adobe.com/experience-manager/release-notes--aem-6-3-cumulative-fix-pack.html

**Comment by godanny86** [comment]
Hi @viveknextrow, I can reproduce this issue on 6.3.2.2. Looks like something was introduced in the Granite UI between SP2 (which works) and CFP 2 (which does not work). Since Service Pack 3 is out I would recommend upgrading to 6.3.3 which will include all of the Security fixes in CFP2: 

https://helpx.adobe.com/experience-manager/6-3/release-notes/sp3-release-notes.html

**Comment by viveknextrow** [comment]
Hello @godanny86 - we had just recently upgraded to 6.3.2.2 from 6.3.1.0. It will be quite challenging to upgrade again, but I will explore. Thank you.

**Comment by godanny86** [comment]
understood @viveknextrow that is annoying. Do you mind verifying that 6.3.3 fixes the issue?

**Comment by viveknextrow** [comment]
Hello @godanny86 - I have tested it in 6.3.3.0 with Asset Share commons version 1.6.10 and it seems to have been working and it is storing the values correctly.

**Comment by davidjgonzalez** [comment]
Documented at: https://adobe-marketing-cloud.github.io/asset-share-commons/pages/search/path/

Marking as won't fix as this is a product issue and the best solution is to update AEM.
