### ISSUE TITLE
Issue while importing this project 

### ISSUE THREAD

**Issue by raj2017selva** [Adobe-Marketing-Cloud/asset-share-commons#347]
While importing this project getting the below error .plz let me know how to resolve the below error not able to start the bundle. i have AEM 6.3 and service pack "AEM-6.3-Service-Pack-1-6.3.1" installed .

```
ERROR* [qtp53145845-2706] org.apache.felix.http.jetty %bundles.pluginTitle: Cannot start (org.osgi.framework.BundleException: Unable to resolve com.adobe.aem.commons.assetshare.core [542](R 542.4): missing requirement [com.adobe.aem.commons.assetshare.core [542](R 542.4)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.wcm.core.components.models.form)(version>=14.1.0)(!(version>=15.0.0))) [caused by: Unable to resolve com.adobe.cq.core.wcm.components.core [517](R 517.1): missing requirement [com.adobe.cq.core.wcm.components.core [517](R 517.1)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.wcm.api.policies)(version>=1.6.0)(!(version>=2.0.0)))] Unresolved requirements: [[com.adobe.aem.commons.assetshare.core [542](R 542.4)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.wcm.core.components.models.form)(version>=14.1.0)(!(version>=15.0.0)))])
org.osgi.framework.BundleException: Unable to resolve com.adobe.aem.commons.assetshare.core [542](R 542.4): missing requirement [com.adobe.aem.commons.assetshare.core [542](R 542.4)] osgi.wiring.package; (&(osgi.wiring.package=co
```

**Comment by davidjgonzalez** [comment]
What version of AEM WCM Core Components are installed on your AEM instance?

**Comment by godanny86** [comment]
Hi @raj2017selva,

I was unable to reproduce this issue on a vanilla instance of AEM 6.3 + Service Pack 1 using Asset Share Commons 1.6.10 (the latest). The version of Core Components that is expected on this environment is at 1.1.0, what version do you see installed on your AEM instance?

![image](https://user-images.githubusercontent.com/8974514/50097958-fcfd2600-01e8-11e9-945c-966aec07a279.png)

![image](https://user-images.githubusercontent.com/8974514/50098115-4cdbed00-01e9-11e9-9250-7cac073b1f49.png)

Are there any other bundles that are in an installed state in your environment?

**Comment by raj2017selva** [comment]
AEM WCM Core Components 2.0.0

**Comment by godanny86** [comment]
Is the Core Component 2.0.0 bundle started? IIRC there were some issues with 2.0.0 version. The Core Components v2.0.4 version is more stable and preferred...

**Comment by godanny86** [comment]
2.0.4 Core Components - https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.0.4. *Note this requires CFP2.

Just an FYI, there is a Service Pack 3 for 6.3 which contains all cumulative and service packs and the latest bug fixes: https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq630/servicepack/AEM-6.3.3.0

**Comment by raj2017selva** [comment]
Hi thanks a lot for ur quick response .now its working fine for me
