### ISSUE TITLE
Issue with datasource component

### ISSUE THREAD

**Issue by aksgh** [Adobe-Marketing-Cloud/asset-share-commons#350]
We are having performance issues which has been traced to datasource component usage on the home page of asset share for creation of filters. This has been customized but we are looking for any known scalability issues OR best practice on the use of it.

Thanks,
Anil

**Comment by davidjgonzalez** [comment]
@aksgh 

1) Which data source exactly?
2) Is your customization based on a data source provided by this project? If so, which and how is it customized?

The data sources used in ASC are simple and don't have much room for poor performance; the 2 "types" are: 

1) Datasource that walks the /oak:index/damAssetLucene data source and collects available indexed properties.
   * This index definition should never get large enough to create a performance impact in the datasource (ie. you would need 1000's of indexRules which isn't a realistic #)
2) Datasource that walks Metadata schemas to determine available Metadata properties.
  * This scales w the number and size of metadata schemas you have defined. Again, the number of total fields would have to be in the 1000's to be perceptible much less great a performance impact.

I'm not sure what your question is wrt to "scalability and best practices" of datasources; they have the same considerations of any code that is executed in the context of a user request; make them fast and efficient as possible; there's nothing special about them.

**Comment by davidjgonzalez** [comment]
Closing since info was not provided. please reopen w requested info.
