### ISSUE TITLE
Asset paths with ampersand in it do not have the link in the share email

### ISSUE THREAD

**Issue by niksvers** [Adobe-Marketing-Cloud/asset-share-commons#358]
**Describe the bug**
When we share an asset using the action button Share, the email received does not have the link to the asset if the asset path contains ampersand '&' in it, for example, in the file name of the asset.

**Environment**
* AEM Version: 6.3.2
* Asset Share Commons Version: 1.6.8
* Author, Publish or both? Both

**To Reproduce**
1. Go to AEM Assets DAM & upload an asset with an ampersand(&) in it's name, for example, 'my-sample-&image.jpg'.
1. Go to the Home page of Asset Share and locate the asset just uploaded.
2. Click on the 'Share' button on the asset tile, or click on the asset tile to go to the Details page & click 'Share' from the action buttons.
3. Enter your email address & click Share.
4. Check your inbox, you should receive an email.

**Expected behavior**
Expected behaviour :  The email should have the link to the asset being shared.
Current behaviour : The email does not have the link to the asset.

**Screenshots**
The email has no link as shown below : 
<img width="900" alt="no-link" src="https://user-images.githubusercontent.com/10622552/51657536-5e3ec300-1ff9-11e9-9582-468f423b10b6.png">

**Additional context**
Had a quick look at the EmailShareServiceImpl.java[1], in the share(Config, ValueMap, String) method it seems that the 'assetPaths' variable is receiving the ampersand(&) encoded in the asset path to '&amp;amp;'.
Then in the getAssetLinkListHtml() method, the 'assetResource' variable resolves to be null as the resourceResolver can't find the asset with the encoded path.

[1] : https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/asset-share-commons-1.6.8/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java

**Comment by davidjgonzalez** [comment]
I think this is another manifestation of incorrect url escaping

https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/340
