### ISSUE TITLE
Needed help on search functionality where the filtering must happen based on range property , for example I want to search all assets having file size of lowerbound=1mb and upperbound=5mb.

### ISSUE THREAD

**Issue by gaurav-poojari** [Adobe-Marketing-Cloud/asset-share-commons#363]
**Question?**
* What piece of functionality do you have a question about?
* What are you trying to achieve?

Documentation can be found here: https://adobe-marketing-cloud.github.io/asset-share-commons/. It might answer your question!

**Comment by davidjgonzalez** [comment]
I believe you'd have to make a new Filter Component that "exposes" the AEM QueryBuilder Range Predicate [1]. The values you'd pass to QB would have to be actual numbers (not "2MB" for example)  and compare against a number-base property (ex. dam:size)


[1] https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/querybuilder-predicate-reference.html#rangeproperty
