### ISSUE TITLE
Inactivate the page until one search operation is being performed

### ISSUE THREAD

**Issue by Lovepreet1994** [Adobe-Marketing-Cloud/asset-share-commons#364]
Hi,

I have one query regarding assets share search facets . When we click on one search filter and get result desired results then we un-check it and then immediately select the other one, it is still showing the results for 1st operation, and 2nd operation is getting ignored. 

This is happening because there are so many assets on asset share so it takes few seconds to perform one operation but end user will not know about this. So can we introduce any loading feature or load button to show that still one operation is being performed?

Regards,
Lovepreet

Documentation can be found here: https://adobe-marketing-cloud.github.io/asset-share-commons/. It might answer your question!

**Comment by godanny86** [comment]
hi @Lovepreet1994 there is a duplicate issue under: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/256

**Comment by godanny86** [comment]
if you don't mind I will close this one and we can prioritize #256 to get in the next milestone
