### ISSUE TITLE
Different Search Results in the same page

### ISSUE THREAD

**Issue by lmarempre** [Adobe-Marketing-Cloud/asset-share-commons#370]
**Question?**
Is it possible to have multiple "Search Results" with the same filter on the same page?

**Error**
If I create two or more "Search results"(/apps/asset-share-commons/components/search/results/result/list) on the same page with different configurations, the results are repeated in all the lists following the properties of the first component, ignoring the configuration of each of the lists.

**Comment by davidjgonzalez** [comment]
You can only have a single search results component on a page. 

There's a ton of unobvious complexity when you try to execute multiple, discrete searches on the same page when the experience is composable (eg. how do you know which filter components go w/ which search results).

What's your use-case of having multiple Search results on a single page? You can certainly have multiple Search PAGES in an ASC impl. For example:

* Main search page: https://aem.enablementadobe.com/content/asset-share-commons/en/light.html
* Whats new search page: https://aem.enablementadobe.com/content/asset-share-commons/en/light/whats-new.html (though this doesnt have matching results :)

**Comment by lmarempre** [comment]
Hello David,
Thanks for the info. The intention is to have several asset categories on the same page, with a single Search Bar, such as the following one:

![assets-categories](https://user-images.githubusercontent.com/47671927/53731372-da3eed00-3e7a-11e9-825d-8127936f6072.png)

Thanks

**Comment by davidjgonzalez** [comment]
@lmarempre yeah, I see what you're going for but - I don't see this being achievable in the ASC framework. there's just too much in terms of query constructions that expects a single Search Results component (and by proxy a single HTML form). 

I think the best solution in the context of using this asset share impl, is having a Filter option component that lets users filter by Images, PDF and Word docs - allowing the user to select which result set is desired,  and then displaying the "type" on the card (which you are already doing, though perhaps your card style needs to be updated to make the type more prominent?)
