### ISSUE TITLE
property name field does not provide jcr:lastModified, type, filesize

### ISSUE THREAD

**Issue by mrozati** [Adobe-Marketing-Cloud/asset-share-commons#374]
**Property name is not provided**
The property name field in the metadata component does not list some of default properties, e.g. `jcr:content/jcr:lastModified` or computed properties `type`, `fileSize`, `resolution` 

This makes the metadata component de-factor uneditable, because as soon as the editor changes something (like date format) and saves the dialog, the `propertyName` is removed and the component shows only the empty text. The component is not reparable without having access to CRX-DE

**Environment**
* AEM Version: 6.3.3.2
* Asset Share Commons Version: 1.6.12
* Author

**To Reproduce**
1. Open a detail page in edit mode, e.g.
http://localhost:4502/editor.html/content/asset-share-commons/en/light/details/image.html
2. Edit metadata component for "Last Modified"
The property name field is empty and `jcr:content/jcr:lastModified` is also not listed in the dropdown
3. Now if you save the component, it disappears and the empty text is displayed instead. 

Same issue applies to metadata components for Type, Size, Resolution and Expired

**Expected behavior**
The property name must be listed in the dropdown properly

**Additional context**
`MetadataSchemaPropertiesImpl` gathers metadata from schema definition in `/conf/global/settings/dam/adminui-extension/metadataschema`
But the default schema does not contain properties like `jcr:lastModified` which makes sense, because it is not supposed to be editable. But this causes the issue that the `MetadataSchemaPropertiesDataSource` do not provide such properties, which are needed in the dialog.

A workaround is to define a custom metadata schema and add the missing properties to it. But imho this rather a hack than a solution.

**Comment by davidjgonzalez** [comment]
@mrozati  see #375 - wdyt?

**Comment by mrozati** [comment]
looks great for me
