### ISSUE TITLE
ShareService method invoked multiple times after bundle refresh (dynamic service references must be volatile)

### ISSUE THREAD

**Issue by mrozati** [Adobe-Marketing-Cloud/asset-share-commons#381]
**Share service references are not updated properly**
[ShareServlet.java#L59](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/ShareServlet.java#L59) has a dynamic reference field to share services. According to the [OSGi spec](https://osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#d0e37828) dynamic service references must be declared as `volatile`.

Since the field is not volatile each time a bundle with a service reference is installed a new 

**Environment**
* AEM Version: 6.3+
* Asset Share Commons Version: 1.6.12
* Author + Publish

**To Reproduce**
1. Deploy a bundle with a share service instance. you could just log a debug message when the share method is called
2. install this bundle several times (this is a real case in test environments with nightly builds)
2. Click on share asset and look in log file
3. you will see the share method is called several times because upon each installation a new instance of service is referenced but the old ones are still there.

**Expected behavior**
Share servlet should keep only one reference for each share service and if one share service is gone, the reference must be removed as well.

**Comment by mrozati** [comment]
I found two other similar issues and fixed them in e8f1db429a7ab66132582366271e5c20b436d006

There are still two `transient` fields in [ComputedPropertiesImpl](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/ComputedPropertiesImpl.java#L57-L58) which I believe must also be `volatile`, since `transient` says only the field must not be serialized. imho serializing objects does not play any role here. @davidjgonzalez what do you think?

**Comment by davidjgonzalez** [comment]
@mrozati reading through the spec again, I’m not clear why these being static greedy result in that behavior.  The share servlet is a singleton so it should only have a reference to a single share service, no?

Static greedy, iucc, should just restart the share servlet, rebinding the shareservice whenever a new one comes available.

I don’t think it hurts to make these dynamic (saves a osgi component restart) but I’m just a bit confused as to how/why this solves the described problem.

Also, it’s probably a good idea to explicitly annotate these fields as dynamic and greedy to ensure the behavior is clear (I didn’t realize the implications of marking a reference volatile prior to this)

**Comment by davidjgonzalez** [comment]
@mrozati wrt to your described issue - I assume you're installing new versions of the same bundle over and over with new versions. I'd expect that when that bundle is replaced it unregisters YOUR ShareService impl, and then re-registers it's on bundle restart. i'm still not understanding how your bundle's (which you replace w/ each deploy) ShareService impl is both still in the ShareServlet's ShareService's Collection and/or it's still hanging around in memory(?). 

It sounds like that Collection of ShareServices just keeps growing and growing and never releases the references to those service objects even after their providing bundle goes away? This sounds like a terrible problem for all non-Unary Static @References - ie. Felix isnt removing these service objects references from the collections when theyre unregistered.
