### ISSUE TITLE
OOB AssetShareCommons Query API,  Adding Extra "/" while creating Query 

### ISSUE THREAD

**Issue by krishh187** [Adobe-Marketing-Cloud/asset-share-commons#407]
We have created custom Application on top of Assetshare commons. But we haven't touched Query generation. The Below queries are failing during indexing. The reason is , the generated Queries from Assetsharecommons API , adding extra "/" before "element". Please find the below queries , which are failing during indexing.

`
/content/dell-assetshare/login/assetshare.results.html HTTP/1.1] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor  Filter(query=select e.[jcr:path] as [jcr:path], e.[jcr:score] as [jcr:score], e.* from [nt:base] as a inner join [nt:base] as b on ischildnode(b, a) inner join [nt:base] as c on ischildnode(c, b) inner join [nt:base] as d on ischildnode(d, c) inner join [dam:Asset] as e on isdescendantnode(e, d) where name(a) = 'Enterprise_Storage' and isdescendantnode(a, '/content/dam/global-asset-library/Products') and name(b) = 'unity' and name(c) = 'dellemc_unity' and name(d) = '880_880f' and e.[jcr:content/contentFragment] is null order by e.[jcr:content/metadata/dell:ingestedDate] desc /* xpath: /jcr:root/content/dam/global-asset-library/Products//Enterprise_Storage/unity/dellemc_unity/_x0038_80_880f//element(*, dam:Asset)[(not(jcr:content/@contentFragment))] order by jcr:content/metadata/@dell:ingestedDate descending */, path=*, property=[:localname=[880_880f]]); consider creating an index or changing the query
`

`
/content/dell-assetshare/login/assetshare.results.html HTTP/1.1] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor  Filter(query=select e.[jcr:path] as [jcr:path], e.[jcr:score] as [jcr:score], e.* from [nt:base] as a inner join [nt:base] as b on ischildnode(b, a) inner join [nt:base] as c on ischildnode(c, b) inner join [nt:base] as d on ischildnode(d, c) inner join [dam:Asset] as e on isdescendantnode(e, d) where name(a) = 'Enterprise_Storage' and isdescendantnode(a, '/content/dam/global-asset-library/Products') and name(b) = 'unity' and name(c) = 'dellemc_unity' and name(d) = 'family' and e.[jcr:content/contentFragment] is null order by e.[jcr:content/metadata/dell:ingestedDate] desc /* xpath: /jcr:root/content/dam/global-asset-library/Products//Enterprise_Storage/unity/dellemc_unity/family//element(*, dam:Asset)[(not(jcr:content/@contentFragment))] order by jcr:content/metadata/@dell:ingestedDate descending */, path=*, property=[:localname=[family]]); consider creating an index or changing the query
`

`
/content/dell-assetshare/login/assetshare.results.html HTTP/1.1] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor  Filter(query=select b.[jcr:path] as [jcr:path], b.[jcr:score] as [jcr:score], b.* from [nt:base] as a inner join [dam:Asset] as b on isdescendantnode(b, a) where name(a) = 'Supporting_Assets' and isdescendantnode(a, '/content/dam/global-asset-library') and b.[jcr:content/contentFragment] is null order by b.[jcr:content/metadata/dell:ingestedDate] desc /* xpath: /jcr:root/content/dam/global-asset-library//Supporting_Assets//element(*, dam:Asset)[(not(jcr:content/@contentFragment))] order by jcr:content/metadata/@dell:ingestedDate descending */, path=/content/dam/global-asset-library//*, property=[:localname=[Supporting_Assets]]); consider creating an index or changing the query
`

`
/content/dell-assetshare/login/assetshare.html HTTP/1.1] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor  Filter(query=select b.[jcr:path] as [jcr:path], b.[jcr:score] as [jcr:score], b.* from [nt:base] as a inner join [dam:Asset] as b on isdescendantnode(b, a) where name(a) = 'templates' and isdescendantnode(a, '/content/dam/global-asset-library/Marcom_Toolkits/demand_marcom/demand_play') and b.[jcr:content/contentFragment] is null order by b.[jcr:content/metadata/dell:ingestedDate] desc /* xpath: /jcr:root/content/dam/global-asset-library/Marcom_Toolkits/demand_marcom/demand_play//templates//element(*, dam:Asset)[(not(jcr:content/@contentFragment))] order by jcr:content/metadata/@dell:ingestedDate descending */, path=/content/dam/global-asset-library/Marcom_Toolkits/demand_marcom/demand_play//*, property=[:localname=[templates]]); consider creating an index or changing the query
/content/dam/global-asset-library/Marcom_Toolkits/fy2019/csg/alienware_m17_r1_gaming_notebook_orion/shared_assets/photography/cs1902g0025_aw_laptop_alienware_m17_print_key-art_gray.psd.form.html HTTP/1.1] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor  Filter(query=select [jcr:path], [jcr:score], * from [nt:base] as a where [cq:formAlias] = 'psd' /* xpath: //*[@cq:formAlias='psd'] */, path=*, property=[cq:formAlias=[psd]]); consider creating an index or changing the query
`

**Comment by davidjgonzalez** [comment]
@krishh187 The extra `/` is just xpath notation; its saying search for all dam:Asset elements under the preceding path.

`/jcr:root/content/dam/global-asset-library/Products//Enterprise_Storage/unity/dellemc_unity/_x0038_80_880f//element(*, dam:Asset)...`

is saying limit result candidates to dam:Assets descendants (any level) under `/jcr:root/content/dam/global-asset-library/Products//Enterprise_Storage/unity/dellemc_unity/_x0038_80_880f`

If it were `/jcr:root/content/dam/global-asset-library/Products//Enterprise_Storage/unity/dellemc_unity/_x0038_80_880f/element(*, dam:Asset)...`
It would be limiting result candidates to be dam:Assets that are direct children of `/jcr:root/content/dam/global-asset-library/Products//Enterprise_Storage/unity/dellemc_unity/_x0038_80_880f`

So I don't think there is a problem. You are Traversing which usually isn't good (though it can be fine). .. so you may need to tune your `damAssetLucene` index and/or adjust your query. You are using custom metadata properties so you absolutely should be tuning your index (it should NOT be left vanilla).
