### ISSUE TITLE
Component Dialog not opening

### ISSUE THREAD

**Issue by hoff9000** [Adobe-Marketing-Cloud/asset-share-commons#412]
**Describe the bug**
Component configure dialog does not open in TouchUI editor. 

**Environment**
* AEM Version: 6.3.3.4
* Asset Share Commons Version: 1.7
* Author, Publish or both: Author 

**To Reproduce**
1. Navigate to TouchUI page editor (http://localhost:4502/editor.html/content/asset-share-commons/en/light.html)
2. Click on any component configure option from toolbar
3. Observe that dialog does not open/ UI unresponsive

**Expected behavior**
Component's dialog opens

**Screenshots**
![image](https://user-images.githubusercontent.com/45748437/58973844-ce164480-8775-11e9-80d5-fa5d7dd53c98.png)

**Additional context**
Other observations -- 
1) Tested and working as expected w/ asset share commons version 1.5 and 1.6.12 on AEM 6.3.3.4. 
2) Tested and working as expected 1.7 on AEM 6.4.4

**Comment by davidjgonzalez** [comment]
Quick Q - is this on EVERY component in ASC? Or just the search results  component?

**Comment by davidjgonzalez** [comment]
Can you also provide the output of the browser's console when you click on open dialog button. Also, asking the obvious but youre clearing your browser cache as you try different versions correct? 

This is quite strange that it works on 6.4.4, but not 6.3.3.4 ..  i dont believe anything changed in 1.6.12 -> 1.7.0 wrt to anything loaded that would page editor chrome... 🤔

**Comment by hoff9000** [comment]
It appears to be every component consistently -- with exception of the search bar component, which works intermittently after x number of page refreshes.  I did notice that that modal/coral.wait spinner on occasion comes up briefly.  Would seems something is firing...  Odd indeed 🤔 (Yes, I tried clearing cache and in Chrome/ MS Edge)

Attaching HAR and console log. 

[localhost-1559838725712_assetcommons_6_3.log](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/3262542/localhost-1559838725712_assetcommons_6_3.log)

**Comment by davidjgonzalez** [comment]
One last q - does this effect non-asc components? Ie Core component proxies or we.retail?

**Comment by hoff9000** [comment]
No problem!  I tested with the WKND tutorial site and WE.RETAIL; and components on both open the config dialog.

**Comment by davidjgonzalez** [comment]
Thanks @hoff9000 - hopefully someone can take a look at this. I won't be back till July to get all the requisite Quickstart/SPs/etc. to reproduce/fix.

**Comment by godanny86** [comment]
hi @hoff9000 I think this is actually caused by a server-side issue. If you look at the AEM error.log located at `<insallation-folder>/crx-quickstart/logs/error.log`: Do you see stack traces like the following:

```
10.06.2019 13:48:10.529 *ERROR* [0:0:0:0:0:0:0:1 [1560199690471] GET /mnt/override/apps/asset-share-commons/components/search/results/_cq_dialog.html/content/asset-share-commons/en/light/jcr:content/root/main/responsivegrid/results HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught SlingException
java.lang.NullPointerException: null
	at com.adobe.aem.commons.assetshare.content.impl.MetadataSchemaPropertiesImpl.collectExtraMetadataProperties(MetadataSchemaPropertiesImpl.java:90)
	at com.adobe.aem.commons.assetshare.content.impl.MetadataSchemaPropertiesImpl.getMetadataProperties(MetadataSchemaPropertiesImpl.java:83)
	at com.adobe.aem.commons.assetshare.content.impl.MetadataSchemaPropertiesImpl.getMetadataProperties(MetadataSchemaPropertiesImpl.java:63)
	at com.adobe.aem.commons.assetshare.search.impl.datasources.OrderablePropertiesDataSource.doGet(OrderablePropertiesDataSource.java:69)
```

I'm guessing this relates to a fix introduced with PR #375...

**Comment by davidjgonzalez** [comment]
Added null checks for the only 2 things that could be null on the lines @godanny86 identified. Rather odd that they aren't null in 6.4 -- though, TBH, I don't see why these would be null - candidates are the cfg object or the method return value, which should return the default value (empty array).

**Comment by godanny86** [comment]
tested your branch locally and that fixes it. Strange that the behavior is different on 6.4+ vs 6.3...
