### ISSUE TITLE
Blank page on new publish instance

### ISSUE THREAD

**Issue by jorgenson112358** [Adobe-Marketing-Cloud/asset-share-commons#413]
Hi, I installed v1.6.12 on an author instance a couple of months ago, got it up and working, got it working on a publish instance at the time. Then had other priorities get in the way of moving the project along. Now in order to get all the setup steps documented, I'm trying to get it working on a completely fresh, brand new publish instance (AEM v6.4). I'm using the same author instance it was originally installed on. What I'm doing is just publishing all pages in the site to the publish instance and all I get is a blank white page. Any idea what I'm doing wrong or setup I'm missing and have long since forgotten?

**Comment by godanny86** [comment]
Hi @jorgenson112358, you will also need the code base (ui.apps, core) installed on the publish instance. An easy way is to replicate the packages from your author instance (or re-upload them on the publish side)
![image](https://user-images.githubusercontent.com/8974514/58991492-3a586e80-879d-11e9-8802-39075c4e0e62.png)

You will also need the templates/policies published as well, but that might happen automatically via the Sites UI when you publish the pages...

**Comment by jorgenson112358** [comment]
My brain was not thinking of straightforward simple solutions. It jumped right into which config, which rule, which toggle did I not set. Thanks for the quick reply!
