### ISSUE TITLE
Asset Rendition Servlet side effects on 6.3.x

### ISSUE THREAD

**Issue by godanny86** [Adobe-Marketing-Cloud/asset-share-commons#421]
**Describe the bug**
Inconsistent behavior with image and video thumbnail renditions related to the Rendition servlet.

**Environment**
* AEM Version: 6.3 + SP 1
* Asset Share Commons Version: 1.7.1-SNAPSHOT (develop branch)
* Author, Publish: Both

**To Reproduce**
1. Navigate to the Search results card and list view. Image thumbnails are blurry.
2. /content/dam/asset-share-commons/en/public/pictures/sarah-dorweiler-357959.jpg.renditions/**card**/asset.rendition
  * expected resolution: **319px**
  * actual resolution: **140px**
3. /content/dam/asset-share-commons/en/public/pictures/sarah-dorweiler-357959.jpg.renditions/**list**/asset.rendition
  * expected resolution: **140px**
  * actual resolution: **48px**

![image](https://user-images.githubusercontent.com/8974514/59469370-7e74f000-8de9-11e9-9a61-7ecb6034dddf.png)

4. Navigate to the Asset Details page for an Image
 * i.e: /editor.html/content/asset-share-commons/en/light/details/image.html/content/dam/asset-share-commons/en/public/pictures/drew-patrick-miller-512.jpg
* Image component does not render at first. Deleting it and re-adding it shows the image. but there is no "legacy" dialog option:
![image](https://user-images.githubusercontent.com/8974514/59469764-9b5df300-8dea-11e9-85a3-2669ed0d57b3.png)

In addition several stack traces are thrown in the logs:

```
sling:authRequestLogin=1 since null
13.06.2019 14:51:35.319 *ERROR* [0:0:0:0:0:0:0:1 [1560462695238] GET /content/asset-share-commons/en/light/details/image.html/content/dam/asset-share-commons/en/public/pictures/drew-patrick-miller-512.jpg HTTP/1.1] org.apache.sling.scripting.sightly.compiler.util.ObjectModel Cannot access method fallback on object com.adobe.aem.commons.assetshare.components.details.impl.ImageImpl@1bc17e75
java.lang.reflect.InvocationTargetException: null
...
13.06.2019 14:52:46.798 *ERROR* [0:0:0:0:0:0:0:1 [1560462766743] GET /content/asset-share-commons/en/light/details/image.html/content/dam/asset-share-commons/en/public/pictures/drew-patrick-miller-512.targetingconfig.json HTTP/1.1] org.apache.sling.scripting.sightly.compiler.util.ObjectModel Cannot access method fallback on object com.adobe.aem.commons.assetshare.components.details.impl.ImageImpl@4d599ef0
...
Caused by: java.lang.NullPointerException: null
	at com.day.text.Text.unescape(Text.java:949)
	at com.day.text.Text.unescape(Text.java:998)
	at com.adobe.aem.commons.assetshare.util.UrlUtil.isEscaped(UrlUtil.java:61)
	at com.adobe.aem.commons.assetshare.util.UrlUtil.escape(UrlUtil.java:44)
	at com.adobe.aem.commons.assetshare.util.UrlUtil.escape(UrlUtil.java:35)
	at com.adobe.aem.commons.assetshare.components.details.impl.ImageImpl.getFallback(ImageImpl.java:159)
	... 276 common frames omitted
```

**Additional context**
This behavior only seems to occur on 6.3.x (I have found the bug on 6.3 + SP1 and 6.3 + SP3, so I'm assuming it is for the entire series)

**Comment by davidjgonzalez** [comment]
@godanny86 thanks for spotting these! Im kinda fixing these blind cause I have the 6.3.0 jar, but not SP1 zip on this computer :(

The first two are config fixes.. idk why 6.3.x doesnt "respect" the params to the servlet.. i added a way to test the OOTB servlet in the PR. I guess it must actually use the static thumbnails and resize from the closest one? (tho it seems to pick the 'wrong' closest one .. youd think it would pick up in size, not down?) .. 🤷‍♀ 

Im not sure what you mean by the Image component "isn't rendering" at first. Does nothing (not even the placeholder show?)  ... or does the image not show? It *should* try to use the `web` rendition using the new asset renditions definition for `web` -- this is based on the Image components `cq:template`.
