### ISSUE TITLE
How to avoid calling of profile.js in asset share 

### ISSUE THREAD

**Issue by Lovepreet1994** [Adobe-Marketing-Cloud/asset-share-commons#437]
Hi,

We are facing one performace issue which is coming due to execution of profile.js. In profile.js "image.prof.thumbnail.128.128.png" image renditions are hard-coded so if any user doesn't add profile pic so its throwing error. We have remove user-menu component form asset share home page but still profile.js is getting called.
How can we stop execution of this?

Regards,
Lovepreet

**Comment by Lovepreet1994** [comment]
![profile](https://user-images.githubusercontent.com/46808411/60642439-8571aa00-9e4d-11e9-95c6-4f15a804036a.PNG)

**Comment by davidjgonzalez** [comment]
hi @lovepreet1994,
When you say it’s a “performance issue” - what exactly do you mean? Is the 404 effecting AEM performance? This should be a very cheap request all things considered.

**Comment by Lovepreet1994** [comment]
Hi David,

Yes i am seeing this error in network tab. Please refer attached screenshot. I have removed references of user-menu form our extended project but still profile.js is getting called. I want to stop execution of profile.js

**Comment by davidjgonzalez** [comment]
You can disable the profile store entirely:
![image](https://user-images.githubusercontent.com/1451868/60769499-9107df80-a09e-11e9-8fbc-365f69c8755d.png)

You should be able to do this via the AEM AUthor UI, but in AEM 6.5.0 at least, this appears to be broken, so i had to go in via CRXDE Lite (as shown above).

**Comment by Lovepreet1994** [comment]
![profile](https://user-images.githubusercontent.com/46808411/60786700-165dc380-a175-11e9-9029-410f7722e3f2.PNG)

**Comment by Lovepreet1994** [comment]
Hi David,

I have made suggested changes but still am getting same error in console.

Regards,
Lovepreet

**Comment by davidjgonzalez** [comment]
Did you create a custom contexthub? You need to disable the profile store in whatever the active ContextHub configuration is actives on your ASC page tree.
