### ISSUE TITLE
.mov video is not playing of size 3 GB

### ISSUE THREAD

**Issue by praveenv2018** [Adobe-Marketing-Cloud/asset-share-commons#438]
Dear Team,

In Asset Share commons video details page, the video with more than 3GB size is not playing. Could you please check this issue.

**Comment by davidjgonzalez** [comment]
@praveenv2018 is the problem the file size? Or something else?

Can you provide screenshots of the network panel where the playback fails?

If you download the MOV file, and open it in your browser directly, will it play back?

**Comment by davidjgonzalez** [comment]
Closing for now. If you can provide more information, please post back.
