### ISSUE TITLE
Show visual feedback when loading more items

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/asset-share-commons#44]
When clicking "Load more" at the bottom of the page it would be nice if a loading indicator gif could be displayed to the user. This is useful when response times are slow.

by way of Andrew k

**Comment by prestoncrawford** [comment]
I'm working with a project where this would be useful as well. I saw this was removed from milestone 1.2.0. Is this no longer being worked on or does [this ticket](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/256) cover that conversation.

**Comment by davidjgonzalez** [comment]
Replaced by https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/256
