### ISSUE TITLE
Lucene Search ranking

### ISSUE THREAD

**Issue by dkmadan2k** [Adobe-Marketing-Cloud/asset-share-commons#444]
We want to modify the default Lucene Search ranking rules in Asset share common.Is there any way we can configure Search ranking as per customer requirements?

**Comment by davidjgonzalez** [comment]
@dkmadan2k can you elaborate on this? most of the ranking rules are done at the Index level (which is orthogonal to ASC use)... the only other thing I could think of, is adding params to fulltext search for query-specific Proximity Matching or Boosts.

[1] http://www.lucenetutorial.com/lucene-query-syntax.html

**Comment by davidjgonzalez** [comment]
Closing. Please re-open if you can provide more details around what youre trying to achieve.
