### ISSUE TITLE
What AEM licenses are required to deploy Asset Share Commons?

### ISSUE THREAD

**Issue by ksurendra** [Adobe-Marketing-Cloud/asset-share-commons#445]
**Question?**
* What piece of functionality do you have a question about?
On deploying and using ASC to AEM

* What are you trying to achieve?
Suggest ASC as a solution to search/view/download assets that are on an AEM Author.

What AEM licenses are required by customers to use ASC on their Author & Publish?

**Comment by davidjgonzalez** [comment]
@ksurendra An AEM Assets license is required to use ASC (an AEM Sites license is not, even though ASC uses AEM Sites technology to serve the Asset Share experience). There may be extra licensing for AEM Publish instances if you do not already have these.

Please talk with your Adobe Rep for customer-specific details; they will be able to let you know what is covered based on your current licenses.
