### ISSUE TITLE
Return Button only works the first time

### ISSUE THREAD

**Issue by godanny86** [Adobe-Marketing-Cloud/asset-share-commons#447]
**Describe the bug**
The "back" button the asset details page only works the first time.

**Environment**
* AEM Version: 6.5, 6.4
* Asset Share Commons Version: latest
* Author, Publish or both? both

**To Reproduce**
1. Perform a keyword search for "bike"
2. Click into a result details page
3. Hit the back button
4. Search is maintained for the keyword "bike"
5. Click into a second result details page
6. Hit the back button
7. Search result is not maintained.

**Expected behavior**
The search result should be maintained until the user performs a new search.

**Screenshots**
This looks to be an issue with the local storage of the returnUrl in that it gets reset the 2nd time:

![image](https://user-images.githubusercontent.com/8974514/65180454-c1121e00-da11-11e9-98ad-f347976e61d4.png)

**Additional context**
Would need to revisit the javascript that populates the returnUrl in local storage: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/navigation.js

**Comment by schmidtkevina** [comment]
I'll take this issue on and fix it.

**Comment by schmidtkevina** [comment]
This issue is now fixed.

**Comment by godanny86** [comment]
Thanks @schmidtkevina !
