### ISSUE TITLE
Unable to download the source code 1.8.0

### ISSUE THREAD

**Issue by mozzvinod** [Adobe-Marketing-Cloud/asset-share-commons#457]
Hi Team,

I  downloaded version 1.8.0 source code from "https://github.com/Adobe-Marketing-Cloud/asset-share-commons/archive/asset-share-commons-1.8.0.zip". But unable to unzip it. I**t says that zip is not valid.**

Could you please help. I need it urgently so solve mail template issue. Where I want to in include the direct assets  path as a link rather than adding detail page link.

Regards,
Vinod.

**Comment by davidjgonzalez** [comment]
Works just fine for me. I suggest trying a different unzip tool if youre having problems.
