### ISSUE TITLE
Filter section not working in IE11

### ISSUE THREAD

**Issue by assetshare2018** [Adobe-Marketing-Cloud/asset-share-commons#458]
**Describe the bug**
Filter section is not working in IE11

**Environment**
* AEM Version: 6.5
* Asset Share Commons Version: 1.8.0
* Author, Publish or both? Both

**To Reproduce**
1. Go to asset share home page in IE11. (https://aem.enablementadobe.com/content/asset-share-commons/en/light.html)
2. Select any type from filter section.
3. Click on Apply filter button.
4. See the filters are not applied.

**Expected behavior**
Filter should be working in IE11.

**Screenshots**
![image](https://user-images.githubusercontent.com/43200674/68771642-692d1780-064e-11ea-9ad1-c097c6c90a99.png)

I have selected Document type and applied filter. But you can see filter is not working and image type are coming  in the page.

**Comment by davidjgonzalez** [comment]
@assetshare2018 can you check if there are any Javascript errors and id any Ajax calls get fired off?
Unfortunately i dont have Windows on my computer to troubleshoot this.

**Comment by assetshare2018** [comment]
@davidjgonzalez There is no errors console . but we observed form serialization not happening properly in IE 11,  In form-data.js <<form = $(formEl).serializeArray();>> retuning only four form objects in IE 11 but it other browsers we are getting more form objects (around 29).

**Comment by davidjgonzalez** [comment]
@assetshare2018 Does it break for: https://aem.enablementadobe.com/content/asset-share-commons/en/light.html ?

Using the above URL, can you list out which elements ARE included?

**Comment by davidjgonzalez** [comment]
@assetshare2018  can you see if https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/464 fixes your issue? THanks
