### ISSUE TITLE
Tags filter - initial load does not display as expected on iPad/iPhone

### ISSUE THREAD

**Issue by namonte81** [Adobe-Marketing-Cloud/asset-share-commons#460]
**Describe the bug**
Initial load does not display as expected but displays when the next category is expanded on iPad and/or iPhone

**Environment**
* AEM Version: 6.5.0
* Asset Share Commons Version: 1.8.0
* Author, Publish or both? Both

**To Reproduce**
1. Navigate to URL on mobile or tablet https://aem.enablementadobe.com/content/asset-share-commons/en/light.html (you can use the emulator of Safari Develop tools)
2. Click Hamburger to access Filter Menu
3. Expand any of the filters
4. See initial load does not display as expected but displays when the next category is expanded

**Expected behavior**
Category values should be displayed immediately when expanded

**Screenshots**
![ASC-filters-iPad-bug](https://user-images.githubusercontent.com/56603215/69358092-0bf42000-0c65-11ea-8377-3a80cf3ad7c9.png)

**Comment by davidjgonzalez** [comment]
I believe this issue may be fixed in: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/451

**Comment by namonte81** [comment]
@davidjgonzalez Thanks for your quick response! One question....was that fix applied to the demo site? https://aem.enablementadobe.com/content/asset-share-commons/en/light.html 
The issue is reproducible there.

**Comment by davidjgonzalez** [comment]
@namonte81 It is not applied to the demo site yet (it's still pending review/accept/merge to be released)
