### ISSUE TITLE
Is it feasible to convert a jpeg image to png format without transparent background through Asset Share Common Download functionality.

### ISSUE THREAD

**Issue by rajat1020** [Adobe-Marketing-Cloud/asset-share-commons#471]
We have a requirement from business to convert a jpeg image/asset into png without transparent background via Download modal from asset share common framework.

Currently we are storing duplicate images one in jpeg other in png format. If you can help here with some solution that will allow us to exclude uploads of duplicate png in the system.

**Comment by davidjgonzalez** [comment]
@rajat1020 ASC itself doesnt have any sort of image transformers and in the current release the Download Servlet used it eh OOTB servlet, which only can zip up "real" static renditions.

There is a PR open [1] that moves the Download action over to use the ASC Asset Renditions framework [2] which provides a bit more flexibility in what can be downloaded.

Once [1] is merged you would be able to do something like, 

a) Use Dynamic Media to convert an image asset on the fly and add it to a zip
b) Use ACS Commons Named Image Transform Servlet to transform an image on the fly and add it to a zip

In both these cases youd need to be able to have the "transforming mechanism" (DM, ACS Named Image Transform) to be able to programmatically turn the Asset into the desired format; Im not sure if your original binary is a JPEG if that is possible to turn them into transparent PNGs using either of these tools (DM maybe?) .. if your original binary is some other format that can be easily transformed into a transparent png, then this could work.

[1] https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/470
[2] https://adobe-marketing-cloud.github.io/asset-share-commons/pages/development/asset-renditions/

**Comment by rajat1020** [comment]
Thanks a lot David. This helps.

Will explore more on your comments and get back to you in case of any further clarifications.

**Comment by davidjgonzalez** [comment]
Thanks @rajat1020 ! let us know if you figure out a neat solution for this!
