### ISSUE TITLE
Request dispatcher fails for fully qualified url in /etc/mapping

### ISSUE THREAD

**Issue by shajiahmed** [Adobe-Marketing-Cloud/asset-share-commons#472]
When `InternalRedirectRenditionDispatcherImpl.java` invokes `request.getRequestDispatcher()` for image renditions, it does not work with fully qualified resource path that begins with `http://...`  Due to this the image renditions are not returned.  There is no error thrown, just zero bytes are returned by the renditionDispatcher. 

An example of the image rendition:  
`/content/dam/enterprise/headshots/a/Ayodele-Maranatha.AyodeleMO.tif.renditions/card/asset.rendition`

The /etc/mapping  is replacing that URL with a fully qualified URL:  `https://<domain-name.com>/content/dam/enterprise/headshots/a/Ayodele-Maranatha.AyodeleMO.tif.renditions/card/asset.rendition`

which causes the `request.getRequestDispatcher()` to silently fail because the request dispatcher only works for relative URLs.

**Comment by davidjgonzalez** [comment]
It shouldnt work w/ fully qualified URLs - its an *internal* redirect, so just start with the `/`

If you have to have the scheme/host/port then you should add it as an ExternalRedirectRenditionDispatcher config.

**Comment by shajiahmed** [comment]
what changes are required in ExternalRedirectRenditionDispatcher
we haven't modified internal redirect configurations
Here is our config
# Configuration created by Apache Sling JCR Installer
rendition.mappings=["card\=${asset.path}.thumb.319.319.jpg","list\=${asset.path}.thumb.140.140.jpg"]
service.ranking=I"-9001"
label="Search\ Results"
name="asset-share-commons-search-results"
types=[""]
hidden=B"true"

**Comment by davidjgonzalez** [comment]
Ah - i misunderstood! If you set DEBUG log on `InternalRedirectRenditionDispatcherImpl` .. what id the debug message from [1]?

That doesnt have the `http://...` in front of it, does it?  After that point, its just doing an `include` for the resource path, so i assume Sling engine itself it adding the http on? This seems very strange in that its an include?

@justinedelson any ideas id/why a requestDispatcher.include(..) would be using /etc/map to add a hostname to the resourcePath that would break the inclusion? This doesn't sound right to me, but I avoid /etc/map as well.

[1] https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/InternalRedirectRenditionDispatcherImpl.java#L117
