### ISSUE TITLE
Login/Logout issue –After Apache Jackrabbit Oak TokenConfiguration expires assets share commons home & details page not redirected to login page

### ISSUE THREAD

**Issue by assetshare2018** [Adobe-Marketing-Cloud/asset-share-commons#477]
**Describe the bug**
We have enabled the authentications for asset share pages and Apache Jackrabbit Oak TokenConfiguration expired after 12 hrs.
After login token expired pages (home & details) is not redirecting immediately to login page, we have more ajax call in search, filter, sorting etc., all pages no reloads needed so in this case after login token expired all functions not working property (it expected) kindly help us to overcome this situation.

**Environment**
* AEM Version: ? 6.5.1
* Asset Share Commons Version: ? 1.6.8
* Author, Publish or both? Publish

**Comment by davidjgonzalez** [comment]
@assetshare2018 ASC relies on as much OOTB AEM functionality as possible, including for authentication and authorization. Please make sure you've configured the ASC pages as you would any other AEM Sites page; instance it sounds like you want to set up the Authentication requirement for the ASC content tree:

![image](https://user-images.githubusercontent.com/1451868/72289387-01c52100-3619-11ea-9aef-a8a93eba4e04.png)

If you are using SAML/IDP you can look up in Adobe Docs how to handle these flows.
