### ISSUE TITLE
Metadata form does no close when user clicks on Save and Close after relating an asset

### ISSUE THREAD

**Issue by shajiahmed** [Adobe-Marketing-Cloud/asset-share-commons#482]
**Describe the bug**

**Environment**
* AEM Version: ? 6.4
* Asset Share Commons Version: ?1.8.1
* Author, Publish or both? Author

**To Reproduce**

 1) Go to the Asset folder and open any asset properties.

2) Click on Relate option present on the top and choose any options.
 3) Select the path and Relate the asset with any asset and click on ok.
 4) Click on Save and Close.
 5) Observe: Asset Metadata form reloads and does not close

**Expected behavior**
Asset Metatdata form should close aftyer user clicks on Save and Close after relating an Consent Status Fragment
*Actual behavior:* Metadata form does no close when user clicks on Save and Close after relating an asset
**Screenshots**

**Additional context**

**Comment by davidjgonzalez** [comment]
@shajiahmed im not sure this has anything to do w/ Asset Share Commons. Sounds like an AEM Assets Admin UI bug. 
What makes you think its ASC related?

**Comment by davidjgonzalez** [comment]
@shajiahmed bumping - thoughts?

**Comment by shajiahmed** [comment]
AEM assets work fine, it happens only when relating the asset which is only available in Asset Share commons.
Here is how you can test
1. Open an asset properties
2. Click on relate, select source (or any option) 
3. Select path of asset 
4. popup display saying relation has been created
5. Click OK to dismiss
6. Click on save & close
Expected behavior: It should close immediately
Actual Behaviour: Screen stays with save & close option
Need to click again on this button, then save & close option goes away

**Comment by godanny86** [comment]
hi @shajiahmed are referring to the Related assets feature [0] ? This is not a feature of Asset Share Commons, but a general feature of AEM Assets.

[0] - https://docs.adobe.com/content/help/en/experience-manager-64/assets/managing/related-assets.html

**Comment by shajiahmed** [comment]
Ah, that may be an AEM bug

**Comment by shajiahmed** [comment]
yeah it is an AEM issue not related to Asset Share

**Comment by davidjgonzalez** [comment]
Thanks for confirming @shajiahmed !
