### ISSUE TITLE
Asset Share Commons - Modals policy only shows up 2 of 5 components

### ISSUE THREAD

**Issue by namonte81** [Adobe-Marketing-Cloud/asset-share-commons#491]
Hello! I ran into an issue on my DEV environment with cart download action. 
Basically, the cart component is not showing up and I don't know the reason.

Modals Policy shows up 2 of 5 components: Download Modal (Dynamic Media) and License Agreement Modal (Cart Modal, Download Modal and E-mail Share Modal are not there).
![Modals policy](https://user-images.githubusercontent.com/56603215/73564648-c743ec80-443e-11ea-975b-5c75d23659e4.png)
![Insert component](https://user-images.githubusercontent.com/56603215/73564693-dd51ad00-443e-11ea-8fe9-d7d0dfcfcb26.png)

While inspecting the dev tools, I'm seeing a 403 error when trying to insert a modal component into layout container of the cart page.

<h1>Forbidden</h1>
        <p>Cannot serve request to /mnt/overlay/wcm/core/content/editor/_jcr_content/content/items/content/content/items/styleselector.form.html/content/asset-share-commons/en/light/actions/cart/_jcr_content/root/responsivegrid/*/ in org.apache.sling.servlets.get.DefaultGetServlet</p>

Do you have any idea about the root cause of this? I've checked permissions in AEM and everything looks good.
Thanks in advance!

**Comment by davidjgonzalez** [comment]
@namonte81 sorry for missing this? What version fo ASC are you on? 
Also, could you verify that the componentGroup for the missing modals are the same as the groups for the ones that show up? IF theyre the same, then this is rather perplexing and sounds like it might be an AEM issue.. 🤔

**Comment by namonte81** [comment]
Hey @davidjgonzalez ! Thanks for your response. I had already checked that and was ok. We solved the issue by reinstalling ASC packages.
Thank you!
