### ISSUE TITLE
Download servlet for Asset share

### ISSUE THREAD

**Issue by preetsekhon94** [Adobe-Marketing-Cloud/asset-share-commons#493]
Hi,

Could you please let me know where can i find out download servlet which is used for Asset share for downloading the assets. Are we using AEM's OOTB servlet so is there any custom servlet for Asset share?

Regards,
Lovepreet

**Comment by preetsekhon94** [comment]
@davidjgonzalez

**Comment by davidjgonzalez** [comment]
The OOTB asset download servlet is used in ASC 1.9.x ... the when 2.x will be adjusting that tho
