### ISSUE TITLE
Add an option to the Asset Details template's Metadata component to allow the name to be shown instead of the value

### ISSUE THREAD

**Issue by artdirk** [Adobe-Marketing-Cloud/asset-share-commons#525]
**Is this feature request related to a problem?**
This feature request is not related to a code problem, but we have some business partners who've created metadata schemas where the name is proper English (for example, "Meeting Minutes") while the value has all the words smashed together ("Meetingminutes").

**Describe the solution you'd like**
It would be nice if the Asset Details template's Metadata component included a checkbox that allowed a page author to have the metadata name shown instead if the value in cases like this.

**Describe alternatives you've considered**
We have not yet considered any alternatives to opening an enhancement request.

**Additional context**
Here's an example of a value that would be better represented by the English name:

![image](https://user-images.githubusercontent.com/33265694/82106268-c6288980-96d4-11ea-859a-52127cd7e4f0.png)

**Comment by davidjgonzalez** [comment]
Hi @artdirk! Long time - hope all is well!

I'm a little confused about how they're constructing these metadata schemas that store the values like this? In your screenshot you use Asset Type with value of "Printmediaadvertising" .. is this value (Printmediaadvertising) set via dropdown list/multi-select?
If so, wouldn't the Metadata field's title for this input be "Asset Type" and not "Print Media Advertising" ...

Im confused as to how they are creating 1:1 between the Field title and value and/or what the value would be in doing that.

**Comment by artdirk** [comment]
Hey @davidjgonzalez! Hope all is also well with you, and you're staying safe!

A custom metadata field named "Asset Type" was created, and the JSON used to seed this field looks as follows:

{    "options" :
 [
     {"value" : "Accessorycard","text" : "Accessory Card"},
     {"value" : "Annualreport","text" : "Annual Report"},
     {"value" : "Apparel","text" : "Apparel"},
     ...
 ]
}

Within the Assets UI, when someone wants to select a value for Asset Type they see the "text" options displayed, and once they select an option the "value" is written into the repository for the asset.

Now that I'm talking this through I realize it will be impossible to show the "text" in the Asset Details template's Metadata component because it only has visibility to the value (and not the text) that's set for the Asset Type metadata property.

I was getting the Asset Details template's Metadata component confused with the Search template's Property Filter component (where you need to specify the text and value for each metadata field option).

Sorry for any confusion that was caused, and I'll close this issue.

**Comment by davidjgonzalez** [comment]
You could make a custom computed property that encapsulates this logic fairly easily; you could either maintain the value to text mapping in code if it rarely changes, or if you wanted to get fancy, you could write some code that points to the metadata schema Asset type drop down field node (in /conf) that defines the drop down list, and uses that as your “translation table”
