### ISSUE TITLE
ShareException("At least one asset is required to share")

### ISSUE THREAD

**Issue by namonte81** [Adobe-Marketing-Cloud/asset-share-commons#528]
Hello! Sorry to bother, but I ran into an issue when trying to send an email of shared assets.
I have an asset path value like this: _/content/dam/xxx/electronic-&-electrochemical/electrochemical/photos-e&e/file1.jpg_

The method  **xssCleanData(String[] dirtyData)** is changing that to something like this:  _/content/dam/xxx/electronic-&amp;amp;-electrochemical/electrochemical/photos-e&amp;amp;e/file1.jpg_

Then, when method **share** tries to get the array of assetPaths the above resource path returns null and the **share** method throws the ShareException because the array is empty:
` throw new ShareException("At least one asset is required to share");`

The above code is part of the file: com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java

Any clue how we can solve that issue and prevent the exception for those asset paths contains characters like ampersand? 

Thanks in advance!

**Comment by davidjgonzalez** [comment]
[asset-share-commons.ui.apps-1.9.5-SNAPSHOT.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/4795800/asset-share-commons.ui.apps-1.9.5-SNAPSHOT.zip)

@namonte81  can yo try this out?

**Comment by namonte81** [comment]
> [asset-share-commons.ui.apps-1.9.5-SNAPSHOT.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/4795800/asset-share-commons.ui.apps-1.9.5-SNAPSHOT.zip)
> 
> @namonte81 can you try this out?

Sure @davidjgonzalez , I'll keep you posted! Thank you very much!

**Comment by namonte81** [comment]
@davidjgonzalez the fix worked as expected....thank you!

**Comment by davidjgonzalez** [comment]
@namonte81 this fix is in 1.9.6 which was released yesterday! Thanks for reporting
