### ISSUE TITLE
Log out functionality is not working

### ISSUE THREAD

**Issue by chinny-biztech** [Adobe-Marketing-Cloud/asset-share-commons#53]
Log out functionality is not working( Log out link cannot be clicked ).This basically blocks logout functionality of the user.
![logout_issue](https://user-images.githubusercontent.com/33501275/32585819-72769e76-c553-11e7-8d99-d0e949122a3f.jpg)
This has been tested on Chrome Version 60.0.3112.113 (Official Build) (64-bit) – INCOGNITO MODE on MacBook Pro (Retina, 15-inch, Mid 2015) MAC OS X Yosemite version 10.10.5

Observed on Author-WCMMODE-PREVIEW mode and Publish.

**Comment by davidjgonzalez** [comment]
@chinny-biztech have you updated this link to point to a valid log out end point? This is configured via the User Menu component [1]. They default to "#" (which i suppose isnt a great default)

What is the exact value you are adding to the log out page dialog field? 

Try putting in for log in: `/system/sling/login.html` 
and for log out `/system/sling/logout.html`

[1] https://adobe-marketing-cloud.github.io/asset-share-commons/pages/structure/user-menu/

**Comment by davidjgonzalez** [comment]
@chinny-biztech If you get around to trying the sling login/logout paths - would be interested around your thoughts i it'd be worth updating the default values (or put them in as placeholders or fieldDescriptions, etc.) for the User Menu. I can appreciate how its not readily apparent that these require configuring on the template (and/or what values you need to put in).

**Comment by chinny-biztech** [comment]
Hi @davidjgonzalez , I have actually updated and published the template changes 2 times. I have checked on both Author(Preview mode) and Publish. I have cleared all my page cache and tried on incognito mode. But still I can't see it is working.  
Steps followed.
1.) Edit template.
2.) Configure User Menu component
3.) Updated Log in and Log out links ( like you said I have tried /system/sling/login.html /system/sling/loginout.html even http://www.google.com.au)
4.) Published the template
5.) Cleared page cache restarted chrome and opened in incognito mode
6.) Check on both author and publish. Still can't click on Log in and Log out.

Can you please tell me am I missing any step here?

**Comment by chinny-biztech** [comment]
Hi @davidjgonzalez , regarding your previous comment, I personally don't like to have values like # for log in & log out links. This can be very easily ignored to configure. But when deciding default values, we also need to consider scenarios such as SAML authentication and CRX default authentication.

**Comment by davidjgonzalez** [comment]
@chinny-biztech so you've configured the login and logout path values on the template, and published them, and the href's for those links point at are still "#" and not your  updated values?

Do those updated values render on Author?

**Comment by godanny86** [comment]
yeah looks like a bug. I'll take a closer look...

**Comment by godanny86** [comment]
@chinny-biztech checkout PR #57

**Comment by rajat1020** [comment]
@davidjgonzalez  Is this issue fixed now for Asset Share Commons?
