### ISSUE TITLE
403 Error on Dispatcher for *.partial.html

### ISSUE THREAD

**Issue by juliaetate** [Adobe-Marketing-Cloud/asset-share-commons#533]
I have Asset Share Commons set up as part of a site, and everything is working as expected except for the Share functionality. We aren't using the Cart or Download modals, only Share, and when the Share button is clicked on the dispatcher, there is a 403 error on the file at /assets/actions/share.partial.html. The Share page will open without error if I put the full URL into the browser, with and without partial. The modal works correctly on the publishers and author.

I don't know enough about the dispatcher settings to figure out how to authorize the modal. I don't see anything relevant on the ASC site or in the issues to try to solve this on my own. I've tried adding an allow rule (/type "allow" /url "/content/*.partial.html*") but I'm not sure if I've formatted it correctly. Is there something else I can add or a header I need to put in to allow the modal to work on the dispatcher?

Any help would be appreciated!

**Comment by godanny86** [comment]
Hi @juliaetate if you hit the publish instance directly (not going through the dispatcher) does the modal work? 

If publish functionality is fine you can try something like allow the `.partial` selector:

```
/filter
    ...
    /0999 {
       /type "allow"
       /selectors "partial"
     }
```
More details: https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html

**Comment by juliaetate** [comment]
Yes, the publish works correctly. I will try your suggestion.

**Comment by juliaetate** [comment]
We added this filter to the dispatcher, but the share is still throwing a 403 error. I have tried both of the following filters. Do I need to add a folder level to the URL? Does it make a difference if the error is a POST call?

`/0300  { /type "allow" /url "/content/*.partial.html*" }
/0301  { /type "allow" /selectors "partial" }`

**Comment by godanny86** [comment]
Can you confirm that the 403 error is coming from the dispatcher  and not reaching AEM itself? You should be able to look at the AEM error.log to verify. 

The reason I ask is because it looks like you are doing some URL shortening to remove `/content` and perhaps something is not getting resolved correctly with the shortened URL...

Also double check that the CSRF token is not being blocked either:

```
/0100 { /type "allow" /url "/libs/granite/csrf/token.json" }
```

**Comment by juliaetate** [comment]
We're not doing anything to rewrite the URLs. I've ensured that the CRSF token is allowed, tried several different rules for the dispatcher, and I'm still getting a 403 from the Share button. There's nothing in the error log on authro when I try to hit the dispatcher, but I can't access the dispatcher logs.

I can access the Share URL directly, though, with and without the .partial. 

![share1](https://user-images.githubusercontent.com/18601409/85565835-1c062080-b5f5-11ea-9805-1c9d2a527233.PNG)
![share2](https://user-images.githubusercontent.com/18601409/85565879-23c5c500-b5f5-11ea-9280-32b226ccef1f.PNG)

**Comment by godanny86** [comment]
Ah very interesting. Is there anything logged to the browser console? Is it possible that is related to a cross origin request issue?

**Comment by juliaetate** [comment]
The only thing I'm seeing in the console is the 403 POST error in the screenshot above. I don't have a great grasp on cross origin requests, but I wouldn't think that it would somehow be trying to access a different publisher with the call to the modal. I don't even really understand how the dispatcher stuff works, tbh. I have to go through 3 levels of people just to try to get updates made to it. The error looks similar to other errors we had with profile nodes and things like that that were related to dispatcher filters, which is why I figured that was the problem. I don't have any idea what else to even try to look at to figure this out.

It works on author. It works on the publish instances directly. The path is accessible directly but not when I click the Share modal button. If there is anything else you could think of that I could try, I would definitely appreciate it.

**Comment by godanny86** [comment]
Based on all of the steps you have tried my hunch would be that it has to do with the modal being a **POST** request, whereas viewing the url directly through the browser will be a **GET** request.

Unfortunately this could be a configuration within the dispatcher.any or at the webserver level. I think you'll need to get the log files for both the dispatcher and the webserver to confirm where to update the configuration...

**Comment by davidjgonzalez** [comment]
+1 the AJAX requests to the modals (partials) are POSTs as they pass along potentially long lists of assets paths, and depending on the size/depth of those paths, they can quickly chew up the allowed HTTP GET url size. Sending them as POST params allows the paths list to grow as last as necessary.

**Comment by juliaetate** [comment]
Is there anything I can add to the dispatcher.any that could solve this without seeing the logs? We're only allowing Share to be used for single assets if that makes a difference. You can only access the modal from the Details page. We're not using Download or Cart on the site either.

**Comment by godanny86** [comment]
As a quick troubleshooting technique you could effectively disable the dispatcher filter:

```diff
   /filter
      {
       # Deny everything first and then allow specific entries
-      /0001 { /type "deny" /glob "*" }
+      /0001 { /type "allow" /glob "*" }
```

And then methodically add rules back (assuming the above solves the issue). Just keep in mind that the above is **not** a best practice but a way to quickly check if the issue is related to Dispatcher filters.

**Comment by juliaetate** [comment]
@godanny86 Thanks for the tips. 

I was finally able to get a local dispatcher set  up to test the rules for the Share modal, and it worked there. When applied to the dev instance, the modal still doesn't work. I don't have access to the dispatcher directly, but I used the same file provided other than the cache path. Are there any other settings that could be blocking the share that I could ask for?
