### ISSUE TITLE
XSS issue on version-compare and page-compare

### ISSUE THREAD

**Issue by karadhak** [Adobe-Marketing-Cloud/asset-share-commons#545]
**Describe the bug**
XSS issue on version-compare and page-compare tools.

**Environment**
* AEM Version: AEM 6.5 Sp6
* Asset Share Commons Version: 4.8.6
* Author, Publish or both: Author

**To Reproduce**
Click on URL:
1. http://localhost:4502/apps/acs-commons/content/version-compare.html?path=%27%22%3C/div%3E%3Cscript%3Ealert(%27hello%20world%27)%3C/script%3E%22
2. http://localhost:4502/apps/acs-commons/content/page-compare.html?path=%27%22%3C/div%3E%3Cscript%3Ealert(%27hello%20world%27)%3C/script%3E%22

**Expected behavior**
Show error message saying "invalid path"

**Screenshots**
Please see screen shot attached.
![Screen Shot 2020-11-03 at 3 13 34 pm](https://user-images.githubusercontent.com/8425688/97949750-c6365600-1de8-11eb-97d3-568ff4ebf69a.png)

**Comment by godanny86** [comment]
Sorry I think you have the wrong project... Also FWIW these kinds of issues should go through https://helpx.adobe.com/security/alertus.html
