### ISSUE TITLE
Download modal window not working if DMS7 is enabled

### ISSUE THREAD

**Issue by roszpapad** [Adobe-Marketing-Cloud/asset-share-commons#558]
If DMS7 is enabled in the system then the download functionality of ASC fails during the opening of the modal window.

Environment: 
  AEM Version: AEM as a Cloud Service
  Asset Share Commons Version: 2.0.0-SNAPSHOT
  Publish

**To Reproduce**
1. Make sure DMS7 is enabled
2. Publish some assets and try to download them on publisher.

**Expected behavior**
The modal window should open up correctly.

**Screenshots**
![download-bug-log](https://user-images.githubusercontent.com/32868620/102070891-0c2b0480-3e00-11eb-97af-2a3954103b5b.png)

**Additional context**
While we were migrating from on-prem to the cloud we got Adobe assistance so we could fix the issue with their help. I am going to open a PR which will fix the issue

**Comment by roszpapad** [comment]
Should I open the PR or describe the solution here?

**Comment by davidjgonzalez** [comment]
@roszpapad PR would be great! 
You might want to log an Adobe Support issue - this appears to be a problem w product code. 

This issue sounds familiar... I wonder if it was fixed but never released in the 1.x line ..

**Comment by roszpapad** [comment]
Hi @davidjgonzalez 
I don't know if it is a product issue for sure. The fix should happen in https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/impl/AssetDownloadHelperImpl.java line 82. The 6th param should be an empty string instead of null. 

I had a conversation with @arpithaar about this and she said to open an issue here. Maybe she can give you more details since she knows more about these codebases.
