### ISSUE TITLE
Delete functionality not working under templates

### ISSUE THREAD

**Issue by apoorvvermarics** [Adobe-Marketing-Cloud/asset-share-commons#564]
**Describe the bug**
While deleting the template under assets hare commons, delete is not working and I can see error in web browser console.

**Environment**
* AEM Version: 6.5
* Asset Share Commons Version: 1.9.4
* Author, Publish or both Author

**To Reproduce**
Steps to reproduce the behaviour:
Go to https://author-rics-stage.adobecqms.net/libs/wcm/core/content/sites/templates.html/conf/asset-share-commons
Select any template to delete and on click of delete button you will see attached error.
Note:- I have admin rights and to delete/update/read all.

**Expected behavior**
Item should be deleted successfully

**Screenshots**
Attached
![Delete](https://user-images.githubusercontent.com/78332841/106412799-9130b280-646e-11eb-9061-5b2a7832d511.png)
![DeleteNotWorking](https://user-images.githubusercontent.com/78332841/106412802-92fa7600-646e-11eb-9729-25c17d869129.png)

**Additional context**

**Comment by davidjgonzalez** [comment]
This is all controlled by AEM. 
I would take a look at the response of the AJAX call to see what's coming back - its possible its a 500 error HTML page, if that's the case, look at your error log to figure out why the OOTB delete is throwing the error.
Closing for now as it doesnt appear like an ASC issue.
