### ISSUE TITLE
Enable update-changelog GitHub app for this repo

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/asset-share-commons#59]
Could you install the **update-changelog** app on AMC so this repo can use it?

Looks like a really nice GH plug-in this guy made: https://github.com/justinedelson/update-changelog

If we can't install on this org, no worries and feel free to close this issue.

**Comment by justinedelson** [comment]
I added the app (which anyone can do via https://github.com/apps/update-changelog). just waiting on PR #62 to be merged for it to work.

**Comment by davidjgonzalez** [comment]
Thanks - sorry for the bother. I though you had to be an org owner to add an app so repos could use it. Didn’t see that gh apps page.
