### ISSUE TITLE
"add to cart" cta remain even after adding the asset to the cart

### ISSUE THREAD

**Issue by mnougarede** [Adobe-Marketing-Cloud/asset-share-commons#70]
This is an enhancement proposal, but shouldn't you remove the CTA "ADD TO CART" after an asset has been added to the cart in the list and card views ? Otherwise we have a hard time to easily understand what's in the cart from what's not.

Instead you could find a way to show that the asset has already been added to the cart.

Thank you for taking in account this feedback.

**Comment by godanny86** [comment]
Yes this would make for a better user experience. One thing we were trying to avoid was maintaining a separate state client-side. I think it is straight forward to remove/disable the "Add to Cart" button as soon as it is clicked, but preserving this on a consistent basis through multiple searches or page navigation will require a little more effort.

**Comment by davidjgonzalez** [comment]
@mnougarede FYI - its possible we might be seeing a contribution that resolves this issue! 

/cc @kaushalmall

**Comment by kaushalmall** [comment]
seems like we can close this now. @davidjgonzalez @mnougarede

**Comment by davidjgonzalez** [comment]
Closed via #92
