### ISSUE TITLE
[Question] Asset Share Commons Cart Issue - Publish Instance Only

### ISSUE THREAD

**Issue by artdirk** [Adobe-Marketing-Cloud/asset-share-commons#91]
The Asset Share Commons code is working well on our author instance, but after replicating a bunch of code and content packages to our publish instance I’m seeing the following errors in my browser’s JavaScript console when loading an Asset Share page:

![firsterror](https://user-images.githubusercontent.com/33265694/34187233-399ae86c-e4e5-11e7-886e-ba27257158c4.png)

Additionally, if I click on the “ADD TO CART” link I see the following error:

![seconderror](https://user-images.githubusercontent.com/33265694/34187243-45a70104-e4e5-11e7-870d-7dfe28ba1238.png)

And finally, if I click on the shopping cart icon I see the following error:

![thirderror](https://user-images.githubusercontent.com/33265694/34187253-5038618a-e4e5-11e7-8646-2285d5c8e1db.png)

Since everything is working perfectly on our author instance, I suspect that a code package is missing on our publish instance and needs to be replicated from the author to the publish instance, but I’m not sure which code package(s) might contain the ContextHub object.

**Comment by godanny86** [comment]
@artdirk can you check that /etc/cloudsettings/asset-share-commons/contexthub has been published?

**Comment by artdirk** [comment]
Hi @godanny86, /etc/cloudsettings/asset-share-commons/contexthub was already published, but I was able to fix this issue just now by activating the following two packages from our author instance to our publish instance:

- adobe/granite/com.adobe.granite.contexthub.content-0.0.276-CQ610-B0002.zip
- adobe/granite/com.adobe.granite.contexthub.content-1.0.20.zip

This is in our AMS AEM 6.3 development hosted instance, so I'm a bit surprised I needed to activate these packages (my assumption was that all relevant ContextHub packages would be automatically activated from the author instance to the publish instance by AMS).

When I checked our publish instance before doing the activation these packages did appear to be there, so I'll follow up with AMS to see if they have any thoughts on what may have been going on.

Thanks so much for your quick attention and help with this issue!

**Comment by davidjgonzalez** [comment]
@artdirk is your page using your own implementation of the search page? I believe the AEM Contexthub JS should be included via the last line in: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/page/customheaderlibs.html

Sounds like the ASC contexthub cart JS In included, but that OOTB include for context hub is not.

**Comment by artdirk** [comment]
Hi David,

I was speaking with another engineer on my team, and it turns out the package activation I did was actually a “red herring” which only fixed one aspect of the Asset Share functionality without addressing a proper global fix.

We found that the Asset Share pages were not working as expected because nobody had read permissions on the following folders on our publish instance, and this makes sense because our accounts were set up before we deployed the Asset Share Commons code onto it:

- conf (which contains the asset-share-commons folder underneath it)
- etc/cloudsettings (which contains the asset-share-commons and default folders underneath it)

Once we granted read permission on these two folders to the **everyone** group people were able to access Asset Share pages on the publish instance without any issues, so I'm closing this issue.

Thanks again!
Art

**Comment by davidjgonzalez** [comment]
@artdirk thanks for posting  the solution!!

**Comment by artdirk** [comment]
As a follow-up, to avoid modifying the **everyone** group (which is not advised per Adobe's [User Administration and Security](https://helpx.adobe.com/experience-manager/6-3/sites/administering/using/security.html) documentation), we applied these permissions to the **contributor** group instead.
